// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: account_replay_bloc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { CommonReplayStateEnum, commonReplayStateEnumFromJSON, commonReplayStateEnumToJSON } from "./common_blocs";

export const protobufPackage = "";

export interface AccountReplayBlocState {
  state: CommonReplayStateEnum;
  termsVersion: number;
  privacyVersion: number;
  /** base64 encoded events */
  events: { [key: number]: string };
  /** list of sites (created or joined) */
  sitesIds: string[];
}

export interface AccountReplayBlocState_EventsEntry {
  key: number;
  value: string;
}

function createBaseAccountReplayBlocState(): AccountReplayBlocState {
  return { state: 0, termsVersion: 0, privacyVersion: 0, events: {}, sitesIds: [] };
}

export const AccountReplayBlocState = {
  encode(message: AccountReplayBlocState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    if (message.termsVersion !== 0) {
      writer.uint32(16).int32(message.termsVersion);
    }
    if (message.privacyVersion !== 0) {
      writer.uint32(24).int32(message.privacyVersion);
    }
    Object.entries(message.events).forEach(([key, value]) => {
      AccountReplayBlocState_EventsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).ldelim();
    });
    for (const v of message.sitesIds) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AccountReplayBlocState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountReplayBlocState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.termsVersion = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.privacyVersion = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          const entry4 = AccountReplayBlocState_EventsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.events[entry4.key] = entry4.value;
          }
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.sitesIds.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountReplayBlocState {
    return {
      state: isSet(object.state) ? commonReplayStateEnumFromJSON(object.state) : 0,
      termsVersion: isSet(object.termsVersion) ? globalThis.Number(object.termsVersion) : 0,
      privacyVersion: isSet(object.privacyVersion) ? globalThis.Number(object.privacyVersion) : 0,
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
      sitesIds: globalThis.Array.isArray(object?.sitesIds) ? object.sitesIds.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: AccountReplayBlocState): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = commonReplayStateEnumToJSON(message.state);
    }
    if (message.termsVersion !== 0) {
      obj.termsVersion = Math.round(message.termsVersion);
    }
    if (message.privacyVersion !== 0) {
      obj.privacyVersion = Math.round(message.privacyVersion);
    }
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    if (message.sitesIds?.length) {
      obj.sitesIds = message.sitesIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountReplayBlocState>, I>>(base?: I): AccountReplayBlocState {
    return AccountReplayBlocState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountReplayBlocState>, I>>(object: I): AccountReplayBlocState {
    const message = createBaseAccountReplayBlocState();
    message.state = object.state ?? 0;
    message.termsVersion = object.termsVersion ?? 0;
    message.privacyVersion = object.privacyVersion ?? 0;
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.sitesIds = object.sitesIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseAccountReplayBlocState_EventsEntry(): AccountReplayBlocState_EventsEntry {
  return { key: 0, value: "" };
}

export const AccountReplayBlocState_EventsEntry = {
  encode(message: AccountReplayBlocState_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AccountReplayBlocState_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountReplayBlocState_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountReplayBlocState_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AccountReplayBlocState_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountReplayBlocState_EventsEntry>, I>>(
    base?: I,
  ): AccountReplayBlocState_EventsEntry {
    return AccountReplayBlocState_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountReplayBlocState_EventsEntry>, I>>(
    object: I,
  ): AccountReplayBlocState_EventsEntry {
    const message = createBaseAccountReplayBlocState_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
