// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: service_events.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { BloomFilter } from "./bloom_filter";

export const protobufPackage = "";

/**
 * these records are permanently stored in firebase and read by the client,
 * so do not include email or any other PII
 */
export interface ServiceEvent {
  /**
   * note: do not store timestamp here, it can be pulled from firebase if needed
   * the event version, these must be unique and incrementing
   */
  version: number;
  /** user user that stored this event */
  author: number;
  initialEvent?: ServiceEvent_InitialEvent | undefined;
  serviceStatus?: ServiceEvent_ServiceStatus | undefined;
  terms?: ServiceEvent_TermsOfService | undefined;
  privacy?:
    | ServiceEvent_PrivacyPolicy
    | undefined;
  /** add and update the bloom filter */
  addServiceAdmin?:
    | ServiceEvent_AddServiceAdmin
    | undefined;
  /** remove and update the bloom filter */
  removeServiceAdmin?: ServiceEvent_RemoveServiceAdmin | undefined;
  minVersion?:
    | ServiceEvent_MinimumVersionRequired
    | undefined;
  /** updated beta users filter */
  betaUsersFilter?: BloomFilter | undefined;
  updateServiceAdmin?: ServiceEvent_UpdateServiceAdmin | undefined;
  restoreServiceAdmin?: ServiceEvent_RestoreServiceAdmin | undefined;
}

export interface ServiceEvent_InitialEvent {
  instance: string;
  /** alias name for service admin */
  alias: string;
  /** the new bloom filter after the addition of the first user */
  filter?: BloomFilter | undefined;
  appName: string;
  appId: string;
}

export interface ServiceEvent_ServiceStatus {
  unavailable: boolean;
}

export interface ServiceEvent_TermsOfService {
  content: string;
}

export interface ServiceEvent_PrivacyPolicy {
  content: string;
}

export interface ServiceEvent_AddServiceAdmin {
  /** alias name for service admin */
  alias: string;
  /** the new bloom filter after the addition */
  filter?: BloomFilter | undefined;
}

export interface ServiceEvent_RemoveServiceAdmin {
  id: number;
  filter?: BloomFilter | undefined;
}

export interface ServiceEvent_UpdateServiceAdmin {
  id: number;
  alias: string;
  filter?: BloomFilter | undefined;
}

export interface ServiceEvent_RestoreServiceAdmin {
  id: number;
  alias: string;
  filter?: BloomFilter | undefined;
}

export interface ServiceEvent_MinimumVersionRequired {
  value: number;
}

/**
 * The SubmitServiceEvent is passed to the submit bloc handler, so it can
 * contain PII
 */
export interface SubmitServiceEvent {
  event?:
    | ServiceEvent
    | undefined;
  /** some events have an associated email that has to be saved */
  email: string;
  /** the beta users, if any, commas separated email addresses */
  betaUsers: string;
  addServiceAdminEmail: string;
  updateServiceAdminOriginalEmail: string;
  updateServiceAdminNewEmail: string;
  removeServiceAdminEmail: string;
}

/**
 * The ServiceEventRecord is a representation of the actual record stored in the
 * database This record is used just for display purposes in the client
 */
export interface ServiceEventRecord {
  isoDate: string;
  version: number;
  serviceEvent?: ServiceEvent | undefined;
}

function createBaseServiceEvent(): ServiceEvent {
  return {
    version: 0,
    author: 0,
    initialEvent: undefined,
    serviceStatus: undefined,
    terms: undefined,
    privacy: undefined,
    addServiceAdmin: undefined,
    removeServiceAdmin: undefined,
    minVersion: undefined,
    betaUsersFilter: undefined,
    updateServiceAdmin: undefined,
    restoreServiceAdmin: undefined,
  };
}

export const ServiceEvent = {
  encode(message: ServiceEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).int32(message.version);
    }
    if (message.author !== 0) {
      writer.uint32(16).int32(message.author);
    }
    if (message.initialEvent !== undefined) {
      ServiceEvent_InitialEvent.encode(message.initialEvent, writer.uint32(26).fork()).ldelim();
    }
    if (message.serviceStatus !== undefined) {
      ServiceEvent_ServiceStatus.encode(message.serviceStatus, writer.uint32(34).fork()).ldelim();
    }
    if (message.terms !== undefined) {
      ServiceEvent_TermsOfService.encode(message.terms, writer.uint32(42).fork()).ldelim();
    }
    if (message.privacy !== undefined) {
      ServiceEvent_PrivacyPolicy.encode(message.privacy, writer.uint32(50).fork()).ldelim();
    }
    if (message.addServiceAdmin !== undefined) {
      ServiceEvent_AddServiceAdmin.encode(message.addServiceAdmin, writer.uint32(58).fork()).ldelim();
    }
    if (message.removeServiceAdmin !== undefined) {
      ServiceEvent_RemoveServiceAdmin.encode(message.removeServiceAdmin, writer.uint32(66).fork()).ldelim();
    }
    if (message.minVersion !== undefined) {
      ServiceEvent_MinimumVersionRequired.encode(message.minVersion, writer.uint32(74).fork()).ldelim();
    }
    if (message.betaUsersFilter !== undefined) {
      BloomFilter.encode(message.betaUsersFilter, writer.uint32(82).fork()).ldelim();
    }
    if (message.updateServiceAdmin !== undefined) {
      ServiceEvent_UpdateServiceAdmin.encode(message.updateServiceAdmin, writer.uint32(90).fork()).ldelim();
    }
    if (message.restoreServiceAdmin !== undefined) {
      ServiceEvent_RestoreServiceAdmin.encode(message.restoreServiceAdmin, writer.uint32(98).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.author = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.initialEvent = ServiceEvent_InitialEvent.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.serviceStatus = ServiceEvent_ServiceStatus.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.terms = ServiceEvent_TermsOfService.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.privacy = ServiceEvent_PrivacyPolicy.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.addServiceAdmin = ServiceEvent_AddServiceAdmin.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.removeServiceAdmin = ServiceEvent_RemoveServiceAdmin.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.minVersion = ServiceEvent_MinimumVersionRequired.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.betaUsersFilter = BloomFilter.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.updateServiceAdmin = ServiceEvent_UpdateServiceAdmin.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.restoreServiceAdmin = ServiceEvent_RestoreServiceAdmin.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      author: isSet(object.author) ? globalThis.Number(object.author) : 0,
      initialEvent: isSet(object.initialEvent) ? ServiceEvent_InitialEvent.fromJSON(object.initialEvent) : undefined,
      serviceStatus: isSet(object.serviceStatus)
        ? ServiceEvent_ServiceStatus.fromJSON(object.serviceStatus)
        : undefined,
      terms: isSet(object.terms) ? ServiceEvent_TermsOfService.fromJSON(object.terms) : undefined,
      privacy: isSet(object.privacy) ? ServiceEvent_PrivacyPolicy.fromJSON(object.privacy) : undefined,
      addServiceAdmin: isSet(object.addServiceAdmin)
        ? ServiceEvent_AddServiceAdmin.fromJSON(object.addServiceAdmin)
        : undefined,
      removeServiceAdmin: isSet(object.removeServiceAdmin)
        ? ServiceEvent_RemoveServiceAdmin.fromJSON(object.removeServiceAdmin)
        : undefined,
      minVersion: isSet(object.minVersion)
        ? ServiceEvent_MinimumVersionRequired.fromJSON(object.minVersion)
        : undefined,
      betaUsersFilter: isSet(object.betaUsersFilter) ? BloomFilter.fromJSON(object.betaUsersFilter) : undefined,
      updateServiceAdmin: isSet(object.updateServiceAdmin)
        ? ServiceEvent_UpdateServiceAdmin.fromJSON(object.updateServiceAdmin)
        : undefined,
      restoreServiceAdmin: isSet(object.restoreServiceAdmin)
        ? ServiceEvent_RestoreServiceAdmin.fromJSON(object.restoreServiceAdmin)
        : undefined,
    };
  },

  toJSON(message: ServiceEvent): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.author !== 0) {
      obj.author = Math.round(message.author);
    }
    if (message.initialEvent !== undefined) {
      obj.initialEvent = ServiceEvent_InitialEvent.toJSON(message.initialEvent);
    }
    if (message.serviceStatus !== undefined) {
      obj.serviceStatus = ServiceEvent_ServiceStatus.toJSON(message.serviceStatus);
    }
    if (message.terms !== undefined) {
      obj.terms = ServiceEvent_TermsOfService.toJSON(message.terms);
    }
    if (message.privacy !== undefined) {
      obj.privacy = ServiceEvent_PrivacyPolicy.toJSON(message.privacy);
    }
    if (message.addServiceAdmin !== undefined) {
      obj.addServiceAdmin = ServiceEvent_AddServiceAdmin.toJSON(message.addServiceAdmin);
    }
    if (message.removeServiceAdmin !== undefined) {
      obj.removeServiceAdmin = ServiceEvent_RemoveServiceAdmin.toJSON(message.removeServiceAdmin);
    }
    if (message.minVersion !== undefined) {
      obj.minVersion = ServiceEvent_MinimumVersionRequired.toJSON(message.minVersion);
    }
    if (message.betaUsersFilter !== undefined) {
      obj.betaUsersFilter = BloomFilter.toJSON(message.betaUsersFilter);
    }
    if (message.updateServiceAdmin !== undefined) {
      obj.updateServiceAdmin = ServiceEvent_UpdateServiceAdmin.toJSON(message.updateServiceAdmin);
    }
    if (message.restoreServiceAdmin !== undefined) {
      obj.restoreServiceAdmin = ServiceEvent_RestoreServiceAdmin.toJSON(message.restoreServiceAdmin);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent>, I>>(base?: I): ServiceEvent {
    return ServiceEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent>, I>>(object: I): ServiceEvent {
    const message = createBaseServiceEvent();
    message.version = object.version ?? 0;
    message.author = object.author ?? 0;
    message.initialEvent = (object.initialEvent !== undefined && object.initialEvent !== null)
      ? ServiceEvent_InitialEvent.fromPartial(object.initialEvent)
      : undefined;
    message.serviceStatus = (object.serviceStatus !== undefined && object.serviceStatus !== null)
      ? ServiceEvent_ServiceStatus.fromPartial(object.serviceStatus)
      : undefined;
    message.terms = (object.terms !== undefined && object.terms !== null)
      ? ServiceEvent_TermsOfService.fromPartial(object.terms)
      : undefined;
    message.privacy = (object.privacy !== undefined && object.privacy !== null)
      ? ServiceEvent_PrivacyPolicy.fromPartial(object.privacy)
      : undefined;
    message.addServiceAdmin = (object.addServiceAdmin !== undefined && object.addServiceAdmin !== null)
      ? ServiceEvent_AddServiceAdmin.fromPartial(object.addServiceAdmin)
      : undefined;
    message.removeServiceAdmin = (object.removeServiceAdmin !== undefined && object.removeServiceAdmin !== null)
      ? ServiceEvent_RemoveServiceAdmin.fromPartial(object.removeServiceAdmin)
      : undefined;
    message.minVersion = (object.minVersion !== undefined && object.minVersion !== null)
      ? ServiceEvent_MinimumVersionRequired.fromPartial(object.minVersion)
      : undefined;
    message.betaUsersFilter = (object.betaUsersFilter !== undefined && object.betaUsersFilter !== null)
      ? BloomFilter.fromPartial(object.betaUsersFilter)
      : undefined;
    message.updateServiceAdmin = (object.updateServiceAdmin !== undefined && object.updateServiceAdmin !== null)
      ? ServiceEvent_UpdateServiceAdmin.fromPartial(object.updateServiceAdmin)
      : undefined;
    message.restoreServiceAdmin = (object.restoreServiceAdmin !== undefined && object.restoreServiceAdmin !== null)
      ? ServiceEvent_RestoreServiceAdmin.fromPartial(object.restoreServiceAdmin)
      : undefined;
    return message;
  },
};

function createBaseServiceEvent_InitialEvent(): ServiceEvent_InitialEvent {
  return { instance: "", alias: "", filter: undefined, appName: "", appId: "" };
}

export const ServiceEvent_InitialEvent = {
  encode(message: ServiceEvent_InitialEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.instance !== "") {
      writer.uint32(10).string(message.instance);
    }
    if (message.alias !== "") {
      writer.uint32(18).string(message.alias);
    }
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(26).fork()).ldelim();
    }
    if (message.appName !== "") {
      writer.uint32(34).string(message.appName);
    }
    if (message.appId !== "") {
      writer.uint32(42).string(message.appId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_InitialEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_InitialEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.instance = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.appName = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.appId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_InitialEvent {
    return {
      instance: isSet(object.instance) ? globalThis.String(object.instance) : "",
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
      appName: isSet(object.appName) ? globalThis.String(object.appName) : "",
      appId: isSet(object.appId) ? globalThis.String(object.appId) : "",
    };
  },

  toJSON(message: ServiceEvent_InitialEvent): unknown {
    const obj: any = {};
    if (message.instance !== "") {
      obj.instance = message.instance;
    }
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    if (message.appName !== "") {
      obj.appName = message.appName;
    }
    if (message.appId !== "") {
      obj.appId = message.appId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_InitialEvent>, I>>(base?: I): ServiceEvent_InitialEvent {
    return ServiceEvent_InitialEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_InitialEvent>, I>>(object: I): ServiceEvent_InitialEvent {
    const message = createBaseServiceEvent_InitialEvent();
    message.instance = object.instance ?? "";
    message.alias = object.alias ?? "";
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    message.appName = object.appName ?? "";
    message.appId = object.appId ?? "";
    return message;
  },
};

function createBaseServiceEvent_ServiceStatus(): ServiceEvent_ServiceStatus {
  return { unavailable: false };
}

export const ServiceEvent_ServiceStatus = {
  encode(message: ServiceEvent_ServiceStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unavailable !== false) {
      writer.uint32(8).bool(message.unavailable);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_ServiceStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_ServiceStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unavailable = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_ServiceStatus {
    return { unavailable: isSet(object.unavailable) ? globalThis.Boolean(object.unavailable) : false };
  },

  toJSON(message: ServiceEvent_ServiceStatus): unknown {
    const obj: any = {};
    if (message.unavailable !== false) {
      obj.unavailable = message.unavailable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_ServiceStatus>, I>>(base?: I): ServiceEvent_ServiceStatus {
    return ServiceEvent_ServiceStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_ServiceStatus>, I>>(object: I): ServiceEvent_ServiceStatus {
    const message = createBaseServiceEvent_ServiceStatus();
    message.unavailable = object.unavailable ?? false;
    return message;
  },
};

function createBaseServiceEvent_TermsOfService(): ServiceEvent_TermsOfService {
  return { content: "" };
}

export const ServiceEvent_TermsOfService = {
  encode(message: ServiceEvent_TermsOfService, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_TermsOfService {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_TermsOfService();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_TermsOfService {
    return { content: isSet(object.content) ? globalThis.String(object.content) : "" };
  },

  toJSON(message: ServiceEvent_TermsOfService): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_TermsOfService>, I>>(base?: I): ServiceEvent_TermsOfService {
    return ServiceEvent_TermsOfService.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_TermsOfService>, I>>(object: I): ServiceEvent_TermsOfService {
    const message = createBaseServiceEvent_TermsOfService();
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseServiceEvent_PrivacyPolicy(): ServiceEvent_PrivacyPolicy {
  return { content: "" };
}

export const ServiceEvent_PrivacyPolicy = {
  encode(message: ServiceEvent_PrivacyPolicy, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_PrivacyPolicy {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_PrivacyPolicy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_PrivacyPolicy {
    return { content: isSet(object.content) ? globalThis.String(object.content) : "" };
  },

  toJSON(message: ServiceEvent_PrivacyPolicy): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_PrivacyPolicy>, I>>(base?: I): ServiceEvent_PrivacyPolicy {
    return ServiceEvent_PrivacyPolicy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_PrivacyPolicy>, I>>(object: I): ServiceEvent_PrivacyPolicy {
    const message = createBaseServiceEvent_PrivacyPolicy();
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseServiceEvent_AddServiceAdmin(): ServiceEvent_AddServiceAdmin {
  return { alias: "", filter: undefined };
}

export const ServiceEvent_AddServiceAdmin = {
  encode(message: ServiceEvent_AddServiceAdmin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.alias !== "") {
      writer.uint32(10).string(message.alias);
    }
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_AddServiceAdmin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_AddServiceAdmin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_AddServiceAdmin {
    return {
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ServiceEvent_AddServiceAdmin): unknown {
    const obj: any = {};
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_AddServiceAdmin>, I>>(base?: I): ServiceEvent_AddServiceAdmin {
    return ServiceEvent_AddServiceAdmin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_AddServiceAdmin>, I>>(object: I): ServiceEvent_AddServiceAdmin {
    const message = createBaseServiceEvent_AddServiceAdmin();
    message.alias = object.alias ?? "";
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseServiceEvent_RemoveServiceAdmin(): ServiceEvent_RemoveServiceAdmin {
  return { id: 0, filter: undefined };
}

export const ServiceEvent_RemoveServiceAdmin = {
  encode(message: ServiceEvent_RemoveServiceAdmin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_RemoveServiceAdmin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_RemoveServiceAdmin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_RemoveServiceAdmin {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ServiceEvent_RemoveServiceAdmin): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_RemoveServiceAdmin>, I>>(base?: I): ServiceEvent_RemoveServiceAdmin {
    return ServiceEvent_RemoveServiceAdmin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_RemoveServiceAdmin>, I>>(
    object: I,
  ): ServiceEvent_RemoveServiceAdmin {
    const message = createBaseServiceEvent_RemoveServiceAdmin();
    message.id = object.id ?? 0;
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseServiceEvent_UpdateServiceAdmin(): ServiceEvent_UpdateServiceAdmin {
  return { id: 0, alias: "", filter: undefined };
}

export const ServiceEvent_UpdateServiceAdmin = {
  encode(message: ServiceEvent_UpdateServiceAdmin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.alias !== "") {
      writer.uint32(18).string(message.alias);
    }
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_UpdateServiceAdmin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_UpdateServiceAdmin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_UpdateServiceAdmin {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ServiceEvent_UpdateServiceAdmin): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_UpdateServiceAdmin>, I>>(base?: I): ServiceEvent_UpdateServiceAdmin {
    return ServiceEvent_UpdateServiceAdmin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_UpdateServiceAdmin>, I>>(
    object: I,
  ): ServiceEvent_UpdateServiceAdmin {
    const message = createBaseServiceEvent_UpdateServiceAdmin();
    message.id = object.id ?? 0;
    message.alias = object.alias ?? "";
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseServiceEvent_RestoreServiceAdmin(): ServiceEvent_RestoreServiceAdmin {
  return { id: 0, alias: "", filter: undefined };
}

export const ServiceEvent_RestoreServiceAdmin = {
  encode(message: ServiceEvent_RestoreServiceAdmin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.alias !== "") {
      writer.uint32(18).string(message.alias);
    }
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_RestoreServiceAdmin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_RestoreServiceAdmin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_RestoreServiceAdmin {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ServiceEvent_RestoreServiceAdmin): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_RestoreServiceAdmin>, I>>(
    base?: I,
  ): ServiceEvent_RestoreServiceAdmin {
    return ServiceEvent_RestoreServiceAdmin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_RestoreServiceAdmin>, I>>(
    object: I,
  ): ServiceEvent_RestoreServiceAdmin {
    const message = createBaseServiceEvent_RestoreServiceAdmin();
    message.id = object.id ?? 0;
    message.alias = object.alias ?? "";
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseServiceEvent_MinimumVersionRequired(): ServiceEvent_MinimumVersionRequired {
  return { value: 0 };
}

export const ServiceEvent_MinimumVersionRequired = {
  encode(message: ServiceEvent_MinimumVersionRequired, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.value !== 0) {
      writer.uint32(8).int32(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEvent_MinimumVersionRequired {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEvent_MinimumVersionRequired();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.value = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEvent_MinimumVersionRequired {
    return { value: isSet(object.value) ? globalThis.Number(object.value) : 0 };
  },

  toJSON(message: ServiceEvent_MinimumVersionRequired): unknown {
    const obj: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEvent_MinimumVersionRequired>, I>>(
    base?: I,
  ): ServiceEvent_MinimumVersionRequired {
    return ServiceEvent_MinimumVersionRequired.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEvent_MinimumVersionRequired>, I>>(
    object: I,
  ): ServiceEvent_MinimumVersionRequired {
    const message = createBaseServiceEvent_MinimumVersionRequired();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSubmitServiceEvent(): SubmitServiceEvent {
  return {
    event: undefined,
    email: "",
    betaUsers: "",
    addServiceAdminEmail: "",
    updateServiceAdminOriginalEmail: "",
    updateServiceAdminNewEmail: "",
    removeServiceAdminEmail: "",
  };
}

export const SubmitServiceEvent = {
  encode(message: SubmitServiceEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.event !== undefined) {
      ServiceEvent.encode(message.event, writer.uint32(10).fork()).ldelim();
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.betaUsers !== "") {
      writer.uint32(26).string(message.betaUsers);
    }
    if (message.addServiceAdminEmail !== "") {
      writer.uint32(34).string(message.addServiceAdminEmail);
    }
    if (message.updateServiceAdminOriginalEmail !== "") {
      writer.uint32(42).string(message.updateServiceAdminOriginalEmail);
    }
    if (message.updateServiceAdminNewEmail !== "") {
      writer.uint32(50).string(message.updateServiceAdminNewEmail);
    }
    if (message.removeServiceAdminEmail !== "") {
      writer.uint32(58).string(message.removeServiceAdminEmail);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SubmitServiceEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitServiceEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.event = ServiceEvent.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.betaUsers = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.addServiceAdminEmail = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.updateServiceAdminOriginalEmail = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.updateServiceAdminNewEmail = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.removeServiceAdminEmail = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitServiceEvent {
    return {
      event: isSet(object.event) ? ServiceEvent.fromJSON(object.event) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      betaUsers: isSet(object.betaUsers) ? globalThis.String(object.betaUsers) : "",
      addServiceAdminEmail: isSet(object.addServiceAdminEmail) ? globalThis.String(object.addServiceAdminEmail) : "",
      updateServiceAdminOriginalEmail: isSet(object.updateServiceAdminOriginalEmail)
        ? globalThis.String(object.updateServiceAdminOriginalEmail)
        : "",
      updateServiceAdminNewEmail: isSet(object.updateServiceAdminNewEmail)
        ? globalThis.String(object.updateServiceAdminNewEmail)
        : "",
      removeServiceAdminEmail: isSet(object.removeServiceAdminEmail)
        ? globalThis.String(object.removeServiceAdminEmail)
        : "",
    };
  },

  toJSON(message: SubmitServiceEvent): unknown {
    const obj: any = {};
    if (message.event !== undefined) {
      obj.event = ServiceEvent.toJSON(message.event);
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.betaUsers !== "") {
      obj.betaUsers = message.betaUsers;
    }
    if (message.addServiceAdminEmail !== "") {
      obj.addServiceAdminEmail = message.addServiceAdminEmail;
    }
    if (message.updateServiceAdminOriginalEmail !== "") {
      obj.updateServiceAdminOriginalEmail = message.updateServiceAdminOriginalEmail;
    }
    if (message.updateServiceAdminNewEmail !== "") {
      obj.updateServiceAdminNewEmail = message.updateServiceAdminNewEmail;
    }
    if (message.removeServiceAdminEmail !== "") {
      obj.removeServiceAdminEmail = message.removeServiceAdminEmail;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitServiceEvent>, I>>(base?: I): SubmitServiceEvent {
    return SubmitServiceEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitServiceEvent>, I>>(object: I): SubmitServiceEvent {
    const message = createBaseSubmitServiceEvent();
    message.event = (object.event !== undefined && object.event !== null)
      ? ServiceEvent.fromPartial(object.event)
      : undefined;
    message.email = object.email ?? "";
    message.betaUsers = object.betaUsers ?? "";
    message.addServiceAdminEmail = object.addServiceAdminEmail ?? "";
    message.updateServiceAdminOriginalEmail = object.updateServiceAdminOriginalEmail ?? "";
    message.updateServiceAdminNewEmail = object.updateServiceAdminNewEmail ?? "";
    message.removeServiceAdminEmail = object.removeServiceAdminEmail ?? "";
    return message;
  },
};

function createBaseServiceEventRecord(): ServiceEventRecord {
  return { isoDate: "", version: 0, serviceEvent: undefined };
}

export const ServiceEventRecord = {
  encode(message: ServiceEventRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isoDate !== "") {
      writer.uint32(10).string(message.isoDate);
    }
    if (message.version !== 0) {
      writer.uint32(16).int32(message.version);
    }
    if (message.serviceEvent !== undefined) {
      ServiceEvent.encode(message.serviceEvent, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEventRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEventRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.isoDate = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.version = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.serviceEvent = ServiceEvent.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEventRecord {
    return {
      isoDate: isSet(object.isoDate) ? globalThis.String(object.isoDate) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      serviceEvent: isSet(object.serviceEvent) ? ServiceEvent.fromJSON(object.serviceEvent) : undefined,
    };
  },

  toJSON(message: ServiceEventRecord): unknown {
    const obj: any = {};
    if (message.isoDate !== "") {
      obj.isoDate = message.isoDate;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.serviceEvent !== undefined) {
      obj.serviceEvent = ServiceEvent.toJSON(message.serviceEvent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEventRecord>, I>>(base?: I): ServiceEventRecord {
    return ServiceEventRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEventRecord>, I>>(object: I): ServiceEventRecord {
    const message = createBaseServiceEventRecord();
    message.isoDate = object.isoDate ?? "";
    message.version = object.version ?? 0;
    message.serviceEvent = (object.serviceEvent !== undefined && object.serviceEvent !== null)
      ? ServiceEvent.fromPartial(object.serviceEvent)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
