syntax = "proto3";

package hyttahub.example.template;

enum AppReplayStateEnum {
  hydrating = 0;              // startup, not listening yet
  listening = 1;              // listening to non-empty events collection
  uninitializedListening = 2; // listening to an empty events collection
  networkError = 3;           // network error at startup
  permissionDenied = 4;       // permission denied at startup
}

import "app_events.proto";

message AppReplayBlocState {
  map<int32, string> events = 1; // base64 encoded events
  AppReplayStateEnum state = 2;

  string textValue = 3;
  string codeValue = 4;
  bool checkboxValue = 5;
  string dropdownValue = 6;
  repeated hyttahub.example.template.AppEvent.ReorderableItem listItems = 7;
}
