name: hyttahub_pocketbase
description: "PocketBase implementations for hyttahub base functionality."
repository: https://github.com/bjorge/hyttahub
version: 0.1.6
# publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  hyttahub: ^0.1.53

  pocketbase: ^0.24.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
