syntax = "proto3";

enum CommonReplayStateEnum {
  hydrating = 0; // startup, not listening yet
  listening = 1; // listening to non-empty events collection
  uninitialized = 2; // listening to an empty events collection
  networkError = 3; // network error at startup
  permissionDenied = 4; // permission denied at startup
}

message CommonReplayBlocEvent {
  oneof event_type {
    bool listen = 1; // true or false
    NewEvents newEvents = 2; // internal to bloc
  }
  message NewEvents { map<int32, string> events = 1; }
}

// listen == true -> hydrating -> listening, uninitialized, networkError, permissionDenied
// listen == false -> hydrating

message EventMapProto { map<int32, string> events = 1; }

message CommonSubmitBlocEvent {
  oneof event_type {
    string updatedPayload = 2;
    bool isFormValid = 3;
    SubmitNow submit = 4;
  }
  message SubmitNow {}
}

message CommonSubmitBlocState {
  enum State {
    ready = 0;
    canSubmit = 1;
    submitting = 2;
    error = 3;
    success = 4;
  }
  State state = 1;
  enum ErrorCode {
    none = 0;
    networkError = 1;
    permissionDenied = 2;
  }
  ErrorCode errorCode = 8;
  message SubmitProgress {
    int32 count = 1;
    int32 total = 2;
  }
  SubmitProgress progress = 9;
}