// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: site_name_replay_bloc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { CommonReplayStateEnum, commonReplayStateEnumFromJSON, commonReplayStateEnumToJSON } from "./common_blocs";

export const protobufPackage = "";

export interface SiteNameReplayBlocState {
  state: CommonReplayStateEnum;
  name: string;
  events: { [key: number]: string };
}

export interface SiteNameReplayBlocState_EventsEntry {
  key: number;
  value: string;
}

function createBaseSiteNameReplayBlocState(): SiteNameReplayBlocState {
  return { state: 0, name: "", events: {} };
}

export const SiteNameReplayBlocState = {
  encode(message: SiteNameReplayBlocState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    Object.entries(message.events).forEach(([key, value]) => {
      SiteNameReplayBlocState_EventsEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteNameReplayBlocState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteNameReplayBlocState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          const entry3 = SiteNameReplayBlocState_EventsEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.events[entry3.key] = entry3.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteNameReplayBlocState {
    return {
      state: isSet(object.state) ? commonReplayStateEnumFromJSON(object.state) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: SiteNameReplayBlocState): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = commonReplayStateEnumToJSON(message.state);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteNameReplayBlocState>, I>>(base?: I): SiteNameReplayBlocState {
    return SiteNameReplayBlocState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteNameReplayBlocState>, I>>(object: I): SiteNameReplayBlocState {
    const message = createBaseSiteNameReplayBlocState();
    message.state = object.state ?? 0;
    message.name = object.name ?? "";
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseSiteNameReplayBlocState_EventsEntry(): SiteNameReplayBlocState_EventsEntry {
  return { key: 0, value: "" };
}

export const SiteNameReplayBlocState_EventsEntry = {
  encode(message: SiteNameReplayBlocState_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteNameReplayBlocState_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteNameReplayBlocState_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteNameReplayBlocState_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SiteNameReplayBlocState_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteNameReplayBlocState_EventsEntry>, I>>(
    base?: I,
  ): SiteNameReplayBlocState_EventsEntry {
    return SiteNameReplayBlocState_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteNameReplayBlocState_EventsEntry>, I>>(
    object: I,
  ): SiteNameReplayBlocState_EventsEntry {
    const message = createBaseSiteNameReplayBlocState_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
