// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: site_events.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { AppEventWrapper } from "./app_wrapper";

export const protobufPackage = "";

/**
 * The SiteEvent is persisted in immutable firestore collection
 * do not store email addresses or any other PII in this message
 */
export interface SiteEvent {
  version: number;
  author: number;
  newSite?: SiteEvent_NewSite | undefined;
  addMember?: SiteEvent_AddMember | undefined;
  updateSiteName?:
    | SiteEvent_UpdateSiteName
    | undefined;
  /** the member to remove */
  removeMember?:
    | SiteEvent_RemoveMember
    | undefined;
  /** the member that has left the site */
  leaveSite?: SiteEvent_LeaveSite | undefined;
  restoreMember?: SiteEvent_RestoreMember | undefined;
  updateMember?: SiteEvent_UpdateMember | undefined;
  exportEvent?: SiteEvent_ExportEvent | undefined;
  importEvent?: SiteEvent_ImportEvent | undefined;
  appEvent?: AppEventWrapper | undefined;
}

/** events should be messages to allow for ease in future updates */
export interface SiteEvent_NewSite {
  siteName: string;
  memberName: string;
  instance: string;
}

export interface SiteEvent_AddMember {
  memberName: string;
  admin: boolean;
}

/** admin removes a member from the site */
export interface SiteEvent_RemoveMember {
  memberId: number;
}

export interface SiteEvent_RestoreMember {
  memberId: number;
  memberName: string;
  admin: boolean;
}

export interface SiteEvent_UpdateMember {
  memberId: number;
  memberName: string;
  admin: boolean;
}

/** member leaves the site */
export interface SiteEvent_LeaveSite {
  memberId: number;
}

export interface SiteEvent_UpdateSiteName {
  name: string;
}

export interface SiteEvent_ExportEvent {
  previousSiteId: string;
  appId: string;
  appName: string;
}

export interface SiteEvent_ImportEvent {
  siteName: string;
}

/**
 * The SubmitSiteEvent is passed to the submit bloc handler
 * PII (ex. email) is allowed in this message since not stored to immutable
 * records
 */
export interface SubmitSiteEvent {
  event?:
    | SiteEvent
    | undefined;
  /** the author's email, used to identify the user, required */
  authorEmail: string;
  /** for add member events, the email of the new member */
  addMemberEmail: string;
  /** for remove member events, the email of the member to remove */
  removeMemberEmail: string;
  /** for update member events, the new email of the member */
  updateMemberNewEmail: string;
  /** for update member events, the original email of the member */
  updateMemberOriginalEmail: string;
}

/**
 * The SiteEventRecord is a representation of the actual record stored in the
 * database This record is used for display purposes in the client and to store
 * backup records
 */
export interface SiteEventRecord {
  isoDate: string;
  version: number;
  siteEvent?: SiteEvent | undefined;
}

function createBaseSiteEvent(): SiteEvent {
  return {
    version: 0,
    author: 0,
    newSite: undefined,
    addMember: undefined,
    updateSiteName: undefined,
    removeMember: undefined,
    leaveSite: undefined,
    restoreMember: undefined,
    updateMember: undefined,
    exportEvent: undefined,
    importEvent: undefined,
    appEvent: undefined,
  };
}

export const SiteEvent = {
  encode(message: SiteEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).int32(message.version);
    }
    if (message.author !== 0) {
      writer.uint32(16).int32(message.author);
    }
    if (message.newSite !== undefined) {
      SiteEvent_NewSite.encode(message.newSite, writer.uint32(34).fork()).ldelim();
    }
    if (message.addMember !== undefined) {
      SiteEvent_AddMember.encode(message.addMember, writer.uint32(42).fork()).ldelim();
    }
    if (message.updateSiteName !== undefined) {
      SiteEvent_UpdateSiteName.encode(message.updateSiteName, writer.uint32(50).fork()).ldelim();
    }
    if (message.removeMember !== undefined) {
      SiteEvent_RemoveMember.encode(message.removeMember, writer.uint32(58).fork()).ldelim();
    }
    if (message.leaveSite !== undefined) {
      SiteEvent_LeaveSite.encode(message.leaveSite, writer.uint32(66).fork()).ldelim();
    }
    if (message.restoreMember !== undefined) {
      SiteEvent_RestoreMember.encode(message.restoreMember, writer.uint32(74).fork()).ldelim();
    }
    if (message.updateMember !== undefined) {
      SiteEvent_UpdateMember.encode(message.updateMember, writer.uint32(82).fork()).ldelim();
    }
    if (message.exportEvent !== undefined) {
      SiteEvent_ExportEvent.encode(message.exportEvent, writer.uint32(90).fork()).ldelim();
    }
    if (message.importEvent !== undefined) {
      SiteEvent_ImportEvent.encode(message.importEvent, writer.uint32(98).fork()).ldelim();
    }
    if (message.appEvent !== undefined) {
      AppEventWrapper.encode(message.appEvent, writer.uint32(162).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.author = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.newSite = SiteEvent_NewSite.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.addMember = SiteEvent_AddMember.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.updateSiteName = SiteEvent_UpdateSiteName.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.removeMember = SiteEvent_RemoveMember.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.leaveSite = SiteEvent_LeaveSite.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.restoreMember = SiteEvent_RestoreMember.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.updateMember = SiteEvent_UpdateMember.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.exportEvent = SiteEvent_ExportEvent.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.importEvent = SiteEvent_ImportEvent.decode(reader, reader.uint32());
          continue;
        case 20:
          if (tag !== 162) {
            break;
          }

          message.appEvent = AppEventWrapper.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      author: isSet(object.author) ? globalThis.Number(object.author) : 0,
      newSite: isSet(object.newSite) ? SiteEvent_NewSite.fromJSON(object.newSite) : undefined,
      addMember: isSet(object.addMember) ? SiteEvent_AddMember.fromJSON(object.addMember) : undefined,
      updateSiteName: isSet(object.updateSiteName)
        ? SiteEvent_UpdateSiteName.fromJSON(object.updateSiteName)
        : undefined,
      removeMember: isSet(object.removeMember) ? SiteEvent_RemoveMember.fromJSON(object.removeMember) : undefined,
      leaveSite: isSet(object.leaveSite) ? SiteEvent_LeaveSite.fromJSON(object.leaveSite) : undefined,
      restoreMember: isSet(object.restoreMember) ? SiteEvent_RestoreMember.fromJSON(object.restoreMember) : undefined,
      updateMember: isSet(object.updateMember) ? SiteEvent_UpdateMember.fromJSON(object.updateMember) : undefined,
      exportEvent: isSet(object.exportEvent) ? SiteEvent_ExportEvent.fromJSON(object.exportEvent) : undefined,
      importEvent: isSet(object.importEvent) ? SiteEvent_ImportEvent.fromJSON(object.importEvent) : undefined,
      appEvent: isSet(object.appEvent) ? AppEventWrapper.fromJSON(object.appEvent) : undefined,
    };
  },

  toJSON(message: SiteEvent): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.author !== 0) {
      obj.author = Math.round(message.author);
    }
    if (message.newSite !== undefined) {
      obj.newSite = SiteEvent_NewSite.toJSON(message.newSite);
    }
    if (message.addMember !== undefined) {
      obj.addMember = SiteEvent_AddMember.toJSON(message.addMember);
    }
    if (message.updateSiteName !== undefined) {
      obj.updateSiteName = SiteEvent_UpdateSiteName.toJSON(message.updateSiteName);
    }
    if (message.removeMember !== undefined) {
      obj.removeMember = SiteEvent_RemoveMember.toJSON(message.removeMember);
    }
    if (message.leaveSite !== undefined) {
      obj.leaveSite = SiteEvent_LeaveSite.toJSON(message.leaveSite);
    }
    if (message.restoreMember !== undefined) {
      obj.restoreMember = SiteEvent_RestoreMember.toJSON(message.restoreMember);
    }
    if (message.updateMember !== undefined) {
      obj.updateMember = SiteEvent_UpdateMember.toJSON(message.updateMember);
    }
    if (message.exportEvent !== undefined) {
      obj.exportEvent = SiteEvent_ExportEvent.toJSON(message.exportEvent);
    }
    if (message.importEvent !== undefined) {
      obj.importEvent = SiteEvent_ImportEvent.toJSON(message.importEvent);
    }
    if (message.appEvent !== undefined) {
      obj.appEvent = AppEventWrapper.toJSON(message.appEvent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent>, I>>(base?: I): SiteEvent {
    return SiteEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent>, I>>(object: I): SiteEvent {
    const message = createBaseSiteEvent();
    message.version = object.version ?? 0;
    message.author = object.author ?? 0;
    message.newSite = (object.newSite !== undefined && object.newSite !== null)
      ? SiteEvent_NewSite.fromPartial(object.newSite)
      : undefined;
    message.addMember = (object.addMember !== undefined && object.addMember !== null)
      ? SiteEvent_AddMember.fromPartial(object.addMember)
      : undefined;
    message.updateSiteName = (object.updateSiteName !== undefined && object.updateSiteName !== null)
      ? SiteEvent_UpdateSiteName.fromPartial(object.updateSiteName)
      : undefined;
    message.removeMember = (object.removeMember !== undefined && object.removeMember !== null)
      ? SiteEvent_RemoveMember.fromPartial(object.removeMember)
      : undefined;
    message.leaveSite = (object.leaveSite !== undefined && object.leaveSite !== null)
      ? SiteEvent_LeaveSite.fromPartial(object.leaveSite)
      : undefined;
    message.restoreMember = (object.restoreMember !== undefined && object.restoreMember !== null)
      ? SiteEvent_RestoreMember.fromPartial(object.restoreMember)
      : undefined;
    message.updateMember = (object.updateMember !== undefined && object.updateMember !== null)
      ? SiteEvent_UpdateMember.fromPartial(object.updateMember)
      : undefined;
    message.exportEvent = (object.exportEvent !== undefined && object.exportEvent !== null)
      ? SiteEvent_ExportEvent.fromPartial(object.exportEvent)
      : undefined;
    message.importEvent = (object.importEvent !== undefined && object.importEvent !== null)
      ? SiteEvent_ImportEvent.fromPartial(object.importEvent)
      : undefined;
    message.appEvent = (object.appEvent !== undefined && object.appEvent !== null)
      ? AppEventWrapper.fromPartial(object.appEvent)
      : undefined;
    return message;
  },
};

function createBaseSiteEvent_NewSite(): SiteEvent_NewSite {
  return { siteName: "", memberName: "", instance: "" };
}

export const SiteEvent_NewSite = {
  encode(message: SiteEvent_NewSite, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.siteName !== "") {
      writer.uint32(10).string(message.siteName);
    }
    if (message.memberName !== "") {
      writer.uint32(18).string(message.memberName);
    }
    if (message.instance !== "") {
      writer.uint32(26).string(message.instance);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_NewSite {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_NewSite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.siteName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.memberName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.instance = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_NewSite {
    return {
      siteName: isSet(object.siteName) ? globalThis.String(object.siteName) : "",
      memberName: isSet(object.memberName) ? globalThis.String(object.memberName) : "",
      instance: isSet(object.instance) ? globalThis.String(object.instance) : "",
    };
  },

  toJSON(message: SiteEvent_NewSite): unknown {
    const obj: any = {};
    if (message.siteName !== "") {
      obj.siteName = message.siteName;
    }
    if (message.memberName !== "") {
      obj.memberName = message.memberName;
    }
    if (message.instance !== "") {
      obj.instance = message.instance;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_NewSite>, I>>(base?: I): SiteEvent_NewSite {
    return SiteEvent_NewSite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_NewSite>, I>>(object: I): SiteEvent_NewSite {
    const message = createBaseSiteEvent_NewSite();
    message.siteName = object.siteName ?? "";
    message.memberName = object.memberName ?? "";
    message.instance = object.instance ?? "";
    return message;
  },
};

function createBaseSiteEvent_AddMember(): SiteEvent_AddMember {
  return { memberName: "", admin: false };
}

export const SiteEvent_AddMember = {
  encode(message: SiteEvent_AddMember, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.memberName !== "") {
      writer.uint32(10).string(message.memberName);
    }
    if (message.admin !== false) {
      writer.uint32(16).bool(message.admin);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_AddMember {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_AddMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.memberName = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.admin = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_AddMember {
    return {
      memberName: isSet(object.memberName) ? globalThis.String(object.memberName) : "",
      admin: isSet(object.admin) ? globalThis.Boolean(object.admin) : false,
    };
  },

  toJSON(message: SiteEvent_AddMember): unknown {
    const obj: any = {};
    if (message.memberName !== "") {
      obj.memberName = message.memberName;
    }
    if (message.admin !== false) {
      obj.admin = message.admin;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_AddMember>, I>>(base?: I): SiteEvent_AddMember {
    return SiteEvent_AddMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_AddMember>, I>>(object: I): SiteEvent_AddMember {
    const message = createBaseSiteEvent_AddMember();
    message.memberName = object.memberName ?? "";
    message.admin = object.admin ?? false;
    return message;
  },
};

function createBaseSiteEvent_RemoveMember(): SiteEvent_RemoveMember {
  return { memberId: 0 };
}

export const SiteEvent_RemoveMember = {
  encode(message: SiteEvent_RemoveMember, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.memberId !== 0) {
      writer.uint32(8).int32(message.memberId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_RemoveMember {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_RemoveMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.memberId = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_RemoveMember {
    return { memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0 };
  },

  toJSON(message: SiteEvent_RemoveMember): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_RemoveMember>, I>>(base?: I): SiteEvent_RemoveMember {
    return SiteEvent_RemoveMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_RemoveMember>, I>>(object: I): SiteEvent_RemoveMember {
    const message = createBaseSiteEvent_RemoveMember();
    message.memberId = object.memberId ?? 0;
    return message;
  },
};

function createBaseSiteEvent_RestoreMember(): SiteEvent_RestoreMember {
  return { memberId: 0, memberName: "", admin: false };
}

export const SiteEvent_RestoreMember = {
  encode(message: SiteEvent_RestoreMember, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.memberId !== 0) {
      writer.uint32(8).int32(message.memberId);
    }
    if (message.memberName !== "") {
      writer.uint32(18).string(message.memberName);
    }
    if (message.admin !== false) {
      writer.uint32(24).bool(message.admin);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_RestoreMember {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_RestoreMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.memberId = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.memberName = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.admin = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_RestoreMember {
    return {
      memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0,
      memberName: isSet(object.memberName) ? globalThis.String(object.memberName) : "",
      admin: isSet(object.admin) ? globalThis.Boolean(object.admin) : false,
    };
  },

  toJSON(message: SiteEvent_RestoreMember): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.memberName !== "") {
      obj.memberName = message.memberName;
    }
    if (message.admin !== false) {
      obj.admin = message.admin;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_RestoreMember>, I>>(base?: I): SiteEvent_RestoreMember {
    return SiteEvent_RestoreMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_RestoreMember>, I>>(object: I): SiteEvent_RestoreMember {
    const message = createBaseSiteEvent_RestoreMember();
    message.memberId = object.memberId ?? 0;
    message.memberName = object.memberName ?? "";
    message.admin = object.admin ?? false;
    return message;
  },
};

function createBaseSiteEvent_UpdateMember(): SiteEvent_UpdateMember {
  return { memberId: 0, memberName: "", admin: false };
}

export const SiteEvent_UpdateMember = {
  encode(message: SiteEvent_UpdateMember, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.memberId !== 0) {
      writer.uint32(8).int32(message.memberId);
    }
    if (message.memberName !== "") {
      writer.uint32(18).string(message.memberName);
    }
    if (message.admin !== false) {
      writer.uint32(24).bool(message.admin);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_UpdateMember {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_UpdateMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.memberId = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.memberName = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.admin = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_UpdateMember {
    return {
      memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0,
      memberName: isSet(object.memberName) ? globalThis.String(object.memberName) : "",
      admin: isSet(object.admin) ? globalThis.Boolean(object.admin) : false,
    };
  },

  toJSON(message: SiteEvent_UpdateMember): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.memberName !== "") {
      obj.memberName = message.memberName;
    }
    if (message.admin !== false) {
      obj.admin = message.admin;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_UpdateMember>, I>>(base?: I): SiteEvent_UpdateMember {
    return SiteEvent_UpdateMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_UpdateMember>, I>>(object: I): SiteEvent_UpdateMember {
    const message = createBaseSiteEvent_UpdateMember();
    message.memberId = object.memberId ?? 0;
    message.memberName = object.memberName ?? "";
    message.admin = object.admin ?? false;
    return message;
  },
};

function createBaseSiteEvent_LeaveSite(): SiteEvent_LeaveSite {
  return { memberId: 0 };
}

export const SiteEvent_LeaveSite = {
  encode(message: SiteEvent_LeaveSite, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.memberId !== 0) {
      writer.uint32(8).int32(message.memberId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_LeaveSite {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_LeaveSite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.memberId = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_LeaveSite {
    return { memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0 };
  },

  toJSON(message: SiteEvent_LeaveSite): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_LeaveSite>, I>>(base?: I): SiteEvent_LeaveSite {
    return SiteEvent_LeaveSite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_LeaveSite>, I>>(object: I): SiteEvent_LeaveSite {
    const message = createBaseSiteEvent_LeaveSite();
    message.memberId = object.memberId ?? 0;
    return message;
  },
};

function createBaseSiteEvent_UpdateSiteName(): SiteEvent_UpdateSiteName {
  return { name: "" };
}

export const SiteEvent_UpdateSiteName = {
  encode(message: SiteEvent_UpdateSiteName, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_UpdateSiteName {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_UpdateSiteName();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_UpdateSiteName {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: SiteEvent_UpdateSiteName): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_UpdateSiteName>, I>>(base?: I): SiteEvent_UpdateSiteName {
    return SiteEvent_UpdateSiteName.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_UpdateSiteName>, I>>(object: I): SiteEvent_UpdateSiteName {
    const message = createBaseSiteEvent_UpdateSiteName();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseSiteEvent_ExportEvent(): SiteEvent_ExportEvent {
  return { previousSiteId: "", appId: "", appName: "" };
}

export const SiteEvent_ExportEvent = {
  encode(message: SiteEvent_ExportEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.previousSiteId !== "") {
      writer.uint32(10).string(message.previousSiteId);
    }
    if (message.appId !== "") {
      writer.uint32(18).string(message.appId);
    }
    if (message.appName !== "") {
      writer.uint32(26).string(message.appName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_ExportEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_ExportEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.previousSiteId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.appId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.appName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_ExportEvent {
    return {
      previousSiteId: isSet(object.previousSiteId) ? globalThis.String(object.previousSiteId) : "",
      appId: isSet(object.appId) ? globalThis.String(object.appId) : "",
      appName: isSet(object.appName) ? globalThis.String(object.appName) : "",
    };
  },

  toJSON(message: SiteEvent_ExportEvent): unknown {
    const obj: any = {};
    if (message.previousSiteId !== "") {
      obj.previousSiteId = message.previousSiteId;
    }
    if (message.appId !== "") {
      obj.appId = message.appId;
    }
    if (message.appName !== "") {
      obj.appName = message.appName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_ExportEvent>, I>>(base?: I): SiteEvent_ExportEvent {
    return SiteEvent_ExportEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_ExportEvent>, I>>(object: I): SiteEvent_ExportEvent {
    const message = createBaseSiteEvent_ExportEvent();
    message.previousSiteId = object.previousSiteId ?? "";
    message.appId = object.appId ?? "";
    message.appName = object.appName ?? "";
    return message;
  },
};

function createBaseSiteEvent_ImportEvent(): SiteEvent_ImportEvent {
  return { siteName: "" };
}

export const SiteEvent_ImportEvent = {
  encode(message: SiteEvent_ImportEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.siteName !== "") {
      writer.uint32(10).string(message.siteName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEvent_ImportEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEvent_ImportEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.siteName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEvent_ImportEvent {
    return { siteName: isSet(object.siteName) ? globalThis.String(object.siteName) : "" };
  },

  toJSON(message: SiteEvent_ImportEvent): unknown {
    const obj: any = {};
    if (message.siteName !== "") {
      obj.siteName = message.siteName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEvent_ImportEvent>, I>>(base?: I): SiteEvent_ImportEvent {
    return SiteEvent_ImportEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEvent_ImportEvent>, I>>(object: I): SiteEvent_ImportEvent {
    const message = createBaseSiteEvent_ImportEvent();
    message.siteName = object.siteName ?? "";
    return message;
  },
};

function createBaseSubmitSiteEvent(): SubmitSiteEvent {
  return {
    event: undefined,
    authorEmail: "",
    addMemberEmail: "",
    removeMemberEmail: "",
    updateMemberNewEmail: "",
    updateMemberOriginalEmail: "",
  };
}

export const SubmitSiteEvent = {
  encode(message: SubmitSiteEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.event !== undefined) {
      SiteEvent.encode(message.event, writer.uint32(10).fork()).ldelim();
    }
    if (message.authorEmail !== "") {
      writer.uint32(18).string(message.authorEmail);
    }
    if (message.addMemberEmail !== "") {
      writer.uint32(34).string(message.addMemberEmail);
    }
    if (message.removeMemberEmail !== "") {
      writer.uint32(42).string(message.removeMemberEmail);
    }
    if (message.updateMemberNewEmail !== "") {
      writer.uint32(50).string(message.updateMemberNewEmail);
    }
    if (message.updateMemberOriginalEmail !== "") {
      writer.uint32(58).string(message.updateMemberOriginalEmail);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SubmitSiteEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitSiteEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.event = SiteEvent.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.authorEmail = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.addMemberEmail = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.removeMemberEmail = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.updateMemberNewEmail = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.updateMemberOriginalEmail = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitSiteEvent {
    return {
      event: isSet(object.event) ? SiteEvent.fromJSON(object.event) : undefined,
      authorEmail: isSet(object.authorEmail) ? globalThis.String(object.authorEmail) : "",
      addMemberEmail: isSet(object.addMemberEmail) ? globalThis.String(object.addMemberEmail) : "",
      removeMemberEmail: isSet(object.removeMemberEmail) ? globalThis.String(object.removeMemberEmail) : "",
      updateMemberNewEmail: isSet(object.updateMemberNewEmail) ? globalThis.String(object.updateMemberNewEmail) : "",
      updateMemberOriginalEmail: isSet(object.updateMemberOriginalEmail)
        ? globalThis.String(object.updateMemberOriginalEmail)
        : "",
    };
  },

  toJSON(message: SubmitSiteEvent): unknown {
    const obj: any = {};
    if (message.event !== undefined) {
      obj.event = SiteEvent.toJSON(message.event);
    }
    if (message.authorEmail !== "") {
      obj.authorEmail = message.authorEmail;
    }
    if (message.addMemberEmail !== "") {
      obj.addMemberEmail = message.addMemberEmail;
    }
    if (message.removeMemberEmail !== "") {
      obj.removeMemberEmail = message.removeMemberEmail;
    }
    if (message.updateMemberNewEmail !== "") {
      obj.updateMemberNewEmail = message.updateMemberNewEmail;
    }
    if (message.updateMemberOriginalEmail !== "") {
      obj.updateMemberOriginalEmail = message.updateMemberOriginalEmail;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitSiteEvent>, I>>(base?: I): SubmitSiteEvent {
    return SubmitSiteEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitSiteEvent>, I>>(object: I): SubmitSiteEvent {
    const message = createBaseSubmitSiteEvent();
    message.event = (object.event !== undefined && object.event !== null)
      ? SiteEvent.fromPartial(object.event)
      : undefined;
    message.authorEmail = object.authorEmail ?? "";
    message.addMemberEmail = object.addMemberEmail ?? "";
    message.removeMemberEmail = object.removeMemberEmail ?? "";
    message.updateMemberNewEmail = object.updateMemberNewEmail ?? "";
    message.updateMemberOriginalEmail = object.updateMemberOriginalEmail ?? "";
    return message;
  },
};

function createBaseSiteEventRecord(): SiteEventRecord {
  return { isoDate: "", version: 0, siteEvent: undefined };
}

export const SiteEventRecord = {
  encode(message: SiteEventRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isoDate !== "") {
      writer.uint32(10).string(message.isoDate);
    }
    if (message.version !== 0) {
      writer.uint32(16).int32(message.version);
    }
    if (message.siteEvent !== undefined) {
      SiteEvent.encode(message.siteEvent, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteEventRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteEventRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.isoDate = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.version = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.siteEvent = SiteEvent.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteEventRecord {
    return {
      isoDate: isSet(object.isoDate) ? globalThis.String(object.isoDate) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      siteEvent: isSet(object.siteEvent) ? SiteEvent.fromJSON(object.siteEvent) : undefined,
    };
  },

  toJSON(message: SiteEventRecord): unknown {
    const obj: any = {};
    if (message.isoDate !== "") {
      obj.isoDate = message.isoDate;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.siteEvent !== undefined) {
      obj.siteEvent = SiteEvent.toJSON(message.siteEvent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteEventRecord>, I>>(base?: I): SiteEventRecord {
    return SiteEventRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteEventRecord>, I>>(object: I): SiteEventRecord {
    const message = createBaseSiteEventRecord();
    message.isoDate = object.isoDate ?? "";
    message.version = object.version ?? 0;
    message.siteEvent = (object.siteEvent !== undefined && object.siteEvent !== null)
      ? SiteEvent.fromPartial(object.siteEvent)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
