// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: bloom_filter.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

export interface BloomFilter {
  /** The bit array (Uint8List) */
  bitArray: Uint8Array;
  /** Total number of bits */
  size: number;
  /** Number of hash functions */
  hashCount: number;
}

function createBaseBloomFilter(): BloomFilter {
  return { bitArray: new Uint8Array(0), size: 0, hashCount: 0 };
}

export const BloomFilter = {
  encode(message: BloomFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.bitArray.length !== 0) {
      writer.uint32(10).bytes(message.bitArray);
    }
    if (message.size !== 0) {
      writer.uint32(16).int32(message.size);
    }
    if (message.hashCount !== 0) {
      writer.uint32(24).int32(message.hashCount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BloomFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBloomFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.bitArray = reader.bytes();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.size = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.hashCount = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BloomFilter {
    return {
      bitArray: isSet(object.bitArray) ? bytesFromBase64(object.bitArray) : new Uint8Array(0),
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      hashCount: isSet(object.hashCount) ? globalThis.Number(object.hashCount) : 0,
    };
  },

  toJSON(message: BloomFilter): unknown {
    const obj: any = {};
    if (message.bitArray.length !== 0) {
      obj.bitArray = base64FromBytes(message.bitArray);
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.hashCount !== 0) {
      obj.hashCount = Math.round(message.hashCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BloomFilter>, I>>(base?: I): BloomFilter {
    return BloomFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BloomFilter>, I>>(object: I): BloomFilter {
    const message = createBaseBloomFilter();
    message.bitArray = object.bitArray ?? new Uint8Array(0);
    message.size = object.size ?? 0;
    message.hashCount = object.hashCount ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
