// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: cloud_functions.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "hyttahub";

export interface CloudFunctionsState {
  initial?: CloudFunctionsInitial | undefined;
  loading?: CloudFunctionsLoading | undefined;
  exportSuccess?: ExportSuccess | undefined;
  exportListSuccess?: ExportListSuccess | undefined;
  exportDeleteSuccess?: ExportDeleteSuccess | undefined;
  exportDetailsSuccess?: ExportDetailsSuccess | undefined;
  failure?: CloudFunctionsFailure | undefined;
}

export interface CloudFunctionsInitial {
}

export interface CloudFunctionsLoading {
}

export interface ExportSuccess {
  message: string;
}

export interface ExportFile {
  name: string;
  url: string;
}

export interface ExportListSuccess {
  files: ExportFile[];
}

export interface ExportDeleteSuccess {
}

export interface ExportDetailsSuccess {
  events: string;
}

export interface CloudFunctionsFailure {
  error: string;
}

function createBaseCloudFunctionsState(): CloudFunctionsState {
  return {
    initial: undefined,
    loading: undefined,
    exportSuccess: undefined,
    exportListSuccess: undefined,
    exportDeleteSuccess: undefined,
    exportDetailsSuccess: undefined,
    failure: undefined,
  };
}

export const CloudFunctionsState = {
  encode(message: CloudFunctionsState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.initial !== undefined) {
      CloudFunctionsInitial.encode(message.initial, writer.uint32(10).fork()).ldelim();
    }
    if (message.loading !== undefined) {
      CloudFunctionsLoading.encode(message.loading, writer.uint32(18).fork()).ldelim();
    }
    if (message.exportSuccess !== undefined) {
      ExportSuccess.encode(message.exportSuccess, writer.uint32(26).fork()).ldelim();
    }
    if (message.exportListSuccess !== undefined) {
      ExportListSuccess.encode(message.exportListSuccess, writer.uint32(34).fork()).ldelim();
    }
    if (message.exportDeleteSuccess !== undefined) {
      ExportDeleteSuccess.encode(message.exportDeleteSuccess, writer.uint32(42).fork()).ldelim();
    }
    if (message.exportDetailsSuccess !== undefined) {
      ExportDetailsSuccess.encode(message.exportDetailsSuccess, writer.uint32(50).fork()).ldelim();
    }
    if (message.failure !== undefined) {
      CloudFunctionsFailure.encode(message.failure, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CloudFunctionsState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloudFunctionsState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.initial = CloudFunctionsInitial.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.loading = CloudFunctionsLoading.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.exportSuccess = ExportSuccess.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.exportListSuccess = ExportListSuccess.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.exportDeleteSuccess = ExportDeleteSuccess.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.exportDetailsSuccess = ExportDetailsSuccess.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.failure = CloudFunctionsFailure.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CloudFunctionsState {
    return {
      initial: isSet(object.initial) ? CloudFunctionsInitial.fromJSON(object.initial) : undefined,
      loading: isSet(object.loading) ? CloudFunctionsLoading.fromJSON(object.loading) : undefined,
      exportSuccess: isSet(object.exportSuccess) ? ExportSuccess.fromJSON(object.exportSuccess) : undefined,
      exportListSuccess: isSet(object.exportListSuccess)
        ? ExportListSuccess.fromJSON(object.exportListSuccess)
        : undefined,
      exportDeleteSuccess: isSet(object.exportDeleteSuccess)
        ? ExportDeleteSuccess.fromJSON(object.exportDeleteSuccess)
        : undefined,
      exportDetailsSuccess: isSet(object.exportDetailsSuccess)
        ? ExportDetailsSuccess.fromJSON(object.exportDetailsSuccess)
        : undefined,
      failure: isSet(object.failure) ? CloudFunctionsFailure.fromJSON(object.failure) : undefined,
    };
  },

  toJSON(message: CloudFunctionsState): unknown {
    const obj: any = {};
    if (message.initial !== undefined) {
      obj.initial = CloudFunctionsInitial.toJSON(message.initial);
    }
    if (message.loading !== undefined) {
      obj.loading = CloudFunctionsLoading.toJSON(message.loading);
    }
    if (message.exportSuccess !== undefined) {
      obj.exportSuccess = ExportSuccess.toJSON(message.exportSuccess);
    }
    if (message.exportListSuccess !== undefined) {
      obj.exportListSuccess = ExportListSuccess.toJSON(message.exportListSuccess);
    }
    if (message.exportDeleteSuccess !== undefined) {
      obj.exportDeleteSuccess = ExportDeleteSuccess.toJSON(message.exportDeleteSuccess);
    }
    if (message.exportDetailsSuccess !== undefined) {
      obj.exportDetailsSuccess = ExportDetailsSuccess.toJSON(message.exportDetailsSuccess);
    }
    if (message.failure !== undefined) {
      obj.failure = CloudFunctionsFailure.toJSON(message.failure);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CloudFunctionsState>, I>>(base?: I): CloudFunctionsState {
    return CloudFunctionsState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloudFunctionsState>, I>>(object: I): CloudFunctionsState {
    const message = createBaseCloudFunctionsState();
    message.initial = (object.initial !== undefined && object.initial !== null)
      ? CloudFunctionsInitial.fromPartial(object.initial)
      : undefined;
    message.loading = (object.loading !== undefined && object.loading !== null)
      ? CloudFunctionsLoading.fromPartial(object.loading)
      : undefined;
    message.exportSuccess = (object.exportSuccess !== undefined && object.exportSuccess !== null)
      ? ExportSuccess.fromPartial(object.exportSuccess)
      : undefined;
    message.exportListSuccess = (object.exportListSuccess !== undefined && object.exportListSuccess !== null)
      ? ExportListSuccess.fromPartial(object.exportListSuccess)
      : undefined;
    message.exportDeleteSuccess = (object.exportDeleteSuccess !== undefined && object.exportDeleteSuccess !== null)
      ? ExportDeleteSuccess.fromPartial(object.exportDeleteSuccess)
      : undefined;
    message.exportDetailsSuccess = (object.exportDetailsSuccess !== undefined && object.exportDetailsSuccess !== null)
      ? ExportDetailsSuccess.fromPartial(object.exportDetailsSuccess)
      : undefined;
    message.failure = (object.failure !== undefined && object.failure !== null)
      ? CloudFunctionsFailure.fromPartial(object.failure)
      : undefined;
    return message;
  },
};

function createBaseCloudFunctionsInitial(): CloudFunctionsInitial {
  return {};
}

export const CloudFunctionsInitial = {
  encode(_: CloudFunctionsInitial, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CloudFunctionsInitial {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloudFunctionsInitial();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CloudFunctionsInitial {
    return {};
  },

  toJSON(_: CloudFunctionsInitial): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CloudFunctionsInitial>, I>>(base?: I): CloudFunctionsInitial {
    return CloudFunctionsInitial.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloudFunctionsInitial>, I>>(_: I): CloudFunctionsInitial {
    const message = createBaseCloudFunctionsInitial();
    return message;
  },
};

function createBaseCloudFunctionsLoading(): CloudFunctionsLoading {
  return {};
}

export const CloudFunctionsLoading = {
  encode(_: CloudFunctionsLoading, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CloudFunctionsLoading {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloudFunctionsLoading();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CloudFunctionsLoading {
    return {};
  },

  toJSON(_: CloudFunctionsLoading): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CloudFunctionsLoading>, I>>(base?: I): CloudFunctionsLoading {
    return CloudFunctionsLoading.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloudFunctionsLoading>, I>>(_: I): CloudFunctionsLoading {
    const message = createBaseCloudFunctionsLoading();
    return message;
  },
};

function createBaseExportSuccess(): ExportSuccess {
  return { message: "" };
}

export const ExportSuccess = {
  encode(message: ExportSuccess, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ExportSuccess {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportSuccess {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: ExportSuccess): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportSuccess>, I>>(base?: I): ExportSuccess {
    return ExportSuccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportSuccess>, I>>(object: I): ExportSuccess {
    const message = createBaseExportSuccess();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseExportFile(): ExportFile {
  return { name: "", url: "" };
}

export const ExportFile = {
  encode(message: ExportFile, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ExportFile {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportFile {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: ExportFile): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportFile>, I>>(base?: I): ExportFile {
    return ExportFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportFile>, I>>(object: I): ExportFile {
    const message = createBaseExportFile();
    message.name = object.name ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseExportListSuccess(): ExportListSuccess {
  return { files: [] };
}

export const ExportListSuccess = {
  encode(message: ExportListSuccess, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.files) {
      ExportFile.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ExportListSuccess {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportListSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.files.push(ExportFile.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportListSuccess {
    return {
      files: globalThis.Array.isArray(object?.files) ? object.files.map((e: any) => ExportFile.fromJSON(e)) : [],
    };
  },

  toJSON(message: ExportListSuccess): unknown {
    const obj: any = {};
    if (message.files?.length) {
      obj.files = message.files.map((e) => ExportFile.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportListSuccess>, I>>(base?: I): ExportListSuccess {
    return ExportListSuccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportListSuccess>, I>>(object: I): ExportListSuccess {
    const message = createBaseExportListSuccess();
    message.files = object.files?.map((e) => ExportFile.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExportDeleteSuccess(): ExportDeleteSuccess {
  return {};
}

export const ExportDeleteSuccess = {
  encode(_: ExportDeleteSuccess, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ExportDeleteSuccess {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDeleteSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ExportDeleteSuccess {
    return {};
  },

  toJSON(_: ExportDeleteSuccess): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportDeleteSuccess>, I>>(base?: I): ExportDeleteSuccess {
    return ExportDeleteSuccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportDeleteSuccess>, I>>(_: I): ExportDeleteSuccess {
    const message = createBaseExportDeleteSuccess();
    return message;
  },
};

function createBaseExportDetailsSuccess(): ExportDetailsSuccess {
  return { events: "" };
}

export const ExportDetailsSuccess = {
  encode(message: ExportDetailsSuccess, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.events !== "") {
      writer.uint32(10).string(message.events);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ExportDetailsSuccess {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDetailsSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.events = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportDetailsSuccess {
    return { events: isSet(object.events) ? globalThis.String(object.events) : "" };
  },

  toJSON(message: ExportDetailsSuccess): unknown {
    const obj: any = {};
    if (message.events !== "") {
      obj.events = message.events;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportDetailsSuccess>, I>>(base?: I): ExportDetailsSuccess {
    return ExportDetailsSuccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportDetailsSuccess>, I>>(object: I): ExportDetailsSuccess {
    const message = createBaseExportDetailsSuccess();
    message.events = object.events ?? "";
    return message;
  },
};

function createBaseCloudFunctionsFailure(): CloudFunctionsFailure {
  return { error: "" };
}

export const CloudFunctionsFailure = {
  encode(message: CloudFunctionsFailure, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.error !== "") {
      writer.uint32(10).string(message.error);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CloudFunctionsFailure {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloudFunctionsFailure();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.error = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CloudFunctionsFailure {
    return { error: isSet(object.error) ? globalThis.String(object.error) : "" };
  },

  toJSON(message: CloudFunctionsFailure): unknown {
    const obj: any = {};
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CloudFunctionsFailure>, I>>(base?: I): CloudFunctionsFailure {
    return CloudFunctionsFailure.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloudFunctionsFailure>, I>>(object: I): CloudFunctionsFailure {
    const message = createBaseCloudFunctionsFailure();
    message.error = object.error ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
