// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: common_blocs.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

export enum CommonReplayStateEnum {
  ok = 0,
  fetchingConfig = 1,
  uninitialized = 2,
  networkError = 3,
  permissionDenied = 4,
  UNRECOGNIZED = -1,
}

export function commonReplayStateEnumFromJSON(object: any): CommonReplayStateEnum {
  switch (object) {
    case 0:
    case "ok":
      return CommonReplayStateEnum.ok;
    case 1:
    case "fetchingConfig":
      return CommonReplayStateEnum.fetchingConfig;
    case 2:
    case "uninitialized":
      return CommonReplayStateEnum.uninitialized;
    case 3:
    case "networkError":
      return CommonReplayStateEnum.networkError;
    case 4:
    case "permissionDenied":
      return CommonReplayStateEnum.permissionDenied;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CommonReplayStateEnum.UNRECOGNIZED;
  }
}

export function commonReplayStateEnumToJSON(object: CommonReplayStateEnum): string {
  switch (object) {
    case CommonReplayStateEnum.ok:
      return "ok";
    case CommonReplayStateEnum.fetchingConfig:
      return "fetchingConfig";
    case CommonReplayStateEnum.uninitialized:
      return "uninitialized";
    case CommonReplayStateEnum.networkError:
      return "networkError";
    case CommonReplayStateEnum.permissionDenied:
      return "permissionDenied";
    case CommonReplayStateEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CommonReplayBlocEvent {
  listen?: boolean | undefined;
  newEvents?: CommonReplayBlocEvent_NewEvents | undefined;
  errorOccurred?: string | undefined;
}

export interface CommonReplayBlocEvent_NewEvents {
  events: { [key: number]: string };
}

export interface CommonReplayBlocEvent_NewEvents_EventsEntry {
  key: number;
  value: string;
}

export interface EventMapProto {
  events: { [key: number]: string };
}

export interface EventMapProto_EventsEntry {
  key: number;
  value: string;
}

export interface CommonSubmitBlocEvent {
  updatedPayload?: string | undefined;
  isFormValid?: boolean | undefined;
  submit?: CommonSubmitBlocEvent_SubmitNow | undefined;
}

export interface CommonSubmitBlocEvent_SubmitNow {
}

export interface CommonSubmitBlocState {
  state: CommonSubmitBlocState_State;
  errorCode: CommonSubmitBlocState_ErrorCode;
  progress?: CommonSubmitBlocState_SubmitProgress | undefined;
}

export enum CommonSubmitBlocState_State {
  ready = 0,
  canSubmit = 1,
  submitting = 2,
  error = 3,
  success = 4,
  UNRECOGNIZED = -1,
}

export function commonSubmitBlocState_StateFromJSON(object: any): CommonSubmitBlocState_State {
  switch (object) {
    case 0:
    case "ready":
      return CommonSubmitBlocState_State.ready;
    case 1:
    case "canSubmit":
      return CommonSubmitBlocState_State.canSubmit;
    case 2:
    case "submitting":
      return CommonSubmitBlocState_State.submitting;
    case 3:
    case "error":
      return CommonSubmitBlocState_State.error;
    case 4:
    case "success":
      return CommonSubmitBlocState_State.success;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CommonSubmitBlocState_State.UNRECOGNIZED;
  }
}

export function commonSubmitBlocState_StateToJSON(object: CommonSubmitBlocState_State): string {
  switch (object) {
    case CommonSubmitBlocState_State.ready:
      return "ready";
    case CommonSubmitBlocState_State.canSubmit:
      return "canSubmit";
    case CommonSubmitBlocState_State.submitting:
      return "submitting";
    case CommonSubmitBlocState_State.error:
      return "error";
    case CommonSubmitBlocState_State.success:
      return "success";
    case CommonSubmitBlocState_State.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CommonSubmitBlocState_ErrorCode {
  none = 0,
  networkError = 1,
  permissionDenied = 2,
  UNRECOGNIZED = -1,
}

export function commonSubmitBlocState_ErrorCodeFromJSON(object: any): CommonSubmitBlocState_ErrorCode {
  switch (object) {
    case 0:
    case "none":
      return CommonSubmitBlocState_ErrorCode.none;
    case 1:
    case "networkError":
      return CommonSubmitBlocState_ErrorCode.networkError;
    case 2:
    case "permissionDenied":
      return CommonSubmitBlocState_ErrorCode.permissionDenied;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CommonSubmitBlocState_ErrorCode.UNRECOGNIZED;
  }
}

export function commonSubmitBlocState_ErrorCodeToJSON(object: CommonSubmitBlocState_ErrorCode): string {
  switch (object) {
    case CommonSubmitBlocState_ErrorCode.none:
      return "none";
    case CommonSubmitBlocState_ErrorCode.networkError:
      return "networkError";
    case CommonSubmitBlocState_ErrorCode.permissionDenied:
      return "permissionDenied";
    case CommonSubmitBlocState_ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CommonSubmitBlocState_SubmitProgress {
  count: number;
  total: number;
}

function createBaseCommonReplayBlocEvent(): CommonReplayBlocEvent {
  return { listen: undefined, newEvents: undefined, errorOccurred: undefined };
}

export const CommonReplayBlocEvent = {
  encode(message: CommonReplayBlocEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.listen !== undefined) {
      writer.uint32(8).bool(message.listen);
    }
    if (message.newEvents !== undefined) {
      CommonReplayBlocEvent_NewEvents.encode(message.newEvents, writer.uint32(18).fork()).ldelim();
    }
    if (message.errorOccurred !== undefined) {
      writer.uint32(26).string(message.errorOccurred);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonReplayBlocEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonReplayBlocEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.listen = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.newEvents = CommonReplayBlocEvent_NewEvents.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.errorOccurred = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonReplayBlocEvent {
    return {
      listen: isSet(object.listen) ? globalThis.Boolean(object.listen) : undefined,
      newEvents: isSet(object.newEvents) ? CommonReplayBlocEvent_NewEvents.fromJSON(object.newEvents) : undefined,
      errorOccurred: isSet(object.errorOccurred) ? globalThis.String(object.errorOccurred) : undefined,
    };
  },

  toJSON(message: CommonReplayBlocEvent): unknown {
    const obj: any = {};
    if (message.listen !== undefined) {
      obj.listen = message.listen;
    }
    if (message.newEvents !== undefined) {
      obj.newEvents = CommonReplayBlocEvent_NewEvents.toJSON(message.newEvents);
    }
    if (message.errorOccurred !== undefined) {
      obj.errorOccurred = message.errorOccurred;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonReplayBlocEvent>, I>>(base?: I): CommonReplayBlocEvent {
    return CommonReplayBlocEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonReplayBlocEvent>, I>>(object: I): CommonReplayBlocEvent {
    const message = createBaseCommonReplayBlocEvent();
    message.listen = object.listen ?? undefined;
    message.newEvents = (object.newEvents !== undefined && object.newEvents !== null)
      ? CommonReplayBlocEvent_NewEvents.fromPartial(object.newEvents)
      : undefined;
    message.errorOccurred = object.errorOccurred ?? undefined;
    return message;
  },
};

function createBaseCommonReplayBlocEvent_NewEvents(): CommonReplayBlocEvent_NewEvents {
  return { events: {} };
}

export const CommonReplayBlocEvent_NewEvents = {
  encode(message: CommonReplayBlocEvent_NewEvents, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    Object.entries(message.events).forEach(([key, value]) => {
      CommonReplayBlocEvent_NewEvents_EventsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonReplayBlocEvent_NewEvents {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonReplayBlocEvent_NewEvents();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          const entry1 = CommonReplayBlocEvent_NewEvents_EventsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.events[entry1.key] = entry1.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonReplayBlocEvent_NewEvents {
    return {
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: CommonReplayBlocEvent_NewEvents): unknown {
    const obj: any = {};
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonReplayBlocEvent_NewEvents>, I>>(base?: I): CommonReplayBlocEvent_NewEvents {
    return CommonReplayBlocEvent_NewEvents.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonReplayBlocEvent_NewEvents>, I>>(
    object: I,
  ): CommonReplayBlocEvent_NewEvents {
    const message = createBaseCommonReplayBlocEvent_NewEvents();
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseCommonReplayBlocEvent_NewEvents_EventsEntry(): CommonReplayBlocEvent_NewEvents_EventsEntry {
  return { key: 0, value: "" };
}

export const CommonReplayBlocEvent_NewEvents_EventsEntry = {
  encode(message: CommonReplayBlocEvent_NewEvents_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonReplayBlocEvent_NewEvents_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonReplayBlocEvent_NewEvents_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonReplayBlocEvent_NewEvents_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: CommonReplayBlocEvent_NewEvents_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonReplayBlocEvent_NewEvents_EventsEntry>, I>>(
    base?: I,
  ): CommonReplayBlocEvent_NewEvents_EventsEntry {
    return CommonReplayBlocEvent_NewEvents_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonReplayBlocEvent_NewEvents_EventsEntry>, I>>(
    object: I,
  ): CommonReplayBlocEvent_NewEvents_EventsEntry {
    const message = createBaseCommonReplayBlocEvent_NewEvents_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseEventMapProto(): EventMapProto {
  return { events: {} };
}

export const EventMapProto = {
  encode(message: EventMapProto, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    Object.entries(message.events).forEach(([key, value]) => {
      EventMapProto_EventsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventMapProto {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventMapProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          const entry1 = EventMapProto_EventsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.events[entry1.key] = entry1.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventMapProto {
    return {
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: EventMapProto): unknown {
    const obj: any = {};
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventMapProto>, I>>(base?: I): EventMapProto {
    return EventMapProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventMapProto>, I>>(object: I): EventMapProto {
    const message = createBaseEventMapProto();
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseEventMapProto_EventsEntry(): EventMapProto_EventsEntry {
  return { key: 0, value: "" };
}

export const EventMapProto_EventsEntry = {
  encode(message: EventMapProto_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventMapProto_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventMapProto_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventMapProto_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: EventMapProto_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventMapProto_EventsEntry>, I>>(base?: I): EventMapProto_EventsEntry {
    return EventMapProto_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventMapProto_EventsEntry>, I>>(object: I): EventMapProto_EventsEntry {
    const message = createBaseEventMapProto_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseCommonSubmitBlocEvent(): CommonSubmitBlocEvent {
  return { updatedPayload: undefined, isFormValid: undefined, submit: undefined };
}

export const CommonSubmitBlocEvent = {
  encode(message: CommonSubmitBlocEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.updatedPayload !== undefined) {
      writer.uint32(18).string(message.updatedPayload);
    }
    if (message.isFormValid !== undefined) {
      writer.uint32(24).bool(message.isFormValid);
    }
    if (message.submit !== undefined) {
      CommonSubmitBlocEvent_SubmitNow.encode(message.submit, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonSubmitBlocEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonSubmitBlocEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.updatedPayload = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isFormValid = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.submit = CommonSubmitBlocEvent_SubmitNow.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonSubmitBlocEvent {
    return {
      updatedPayload: isSet(object.updatedPayload) ? globalThis.String(object.updatedPayload) : undefined,
      isFormValid: isSet(object.isFormValid) ? globalThis.Boolean(object.isFormValid) : undefined,
      submit: isSet(object.submit) ? CommonSubmitBlocEvent_SubmitNow.fromJSON(object.submit) : undefined,
    };
  },

  toJSON(message: CommonSubmitBlocEvent): unknown {
    const obj: any = {};
    if (message.updatedPayload !== undefined) {
      obj.updatedPayload = message.updatedPayload;
    }
    if (message.isFormValid !== undefined) {
      obj.isFormValid = message.isFormValid;
    }
    if (message.submit !== undefined) {
      obj.submit = CommonSubmitBlocEvent_SubmitNow.toJSON(message.submit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonSubmitBlocEvent>, I>>(base?: I): CommonSubmitBlocEvent {
    return CommonSubmitBlocEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonSubmitBlocEvent>, I>>(object: I): CommonSubmitBlocEvent {
    const message = createBaseCommonSubmitBlocEvent();
    message.updatedPayload = object.updatedPayload ?? undefined;
    message.isFormValid = object.isFormValid ?? undefined;
    message.submit = (object.submit !== undefined && object.submit !== null)
      ? CommonSubmitBlocEvent_SubmitNow.fromPartial(object.submit)
      : undefined;
    return message;
  },
};

function createBaseCommonSubmitBlocEvent_SubmitNow(): CommonSubmitBlocEvent_SubmitNow {
  return {};
}

export const CommonSubmitBlocEvent_SubmitNow = {
  encode(_: CommonSubmitBlocEvent_SubmitNow, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonSubmitBlocEvent_SubmitNow {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonSubmitBlocEvent_SubmitNow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CommonSubmitBlocEvent_SubmitNow {
    return {};
  },

  toJSON(_: CommonSubmitBlocEvent_SubmitNow): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonSubmitBlocEvent_SubmitNow>, I>>(base?: I): CommonSubmitBlocEvent_SubmitNow {
    return CommonSubmitBlocEvent_SubmitNow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonSubmitBlocEvent_SubmitNow>, I>>(_: I): CommonSubmitBlocEvent_SubmitNow {
    const message = createBaseCommonSubmitBlocEvent_SubmitNow();
    return message;
  },
};

function createBaseCommonSubmitBlocState(): CommonSubmitBlocState {
  return { state: 0, errorCode: 0, progress: undefined };
}

export const CommonSubmitBlocState = {
  encode(message: CommonSubmitBlocState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    if (message.errorCode !== 0) {
      writer.uint32(64).int32(message.errorCode);
    }
    if (message.progress !== undefined) {
      CommonSubmitBlocState_SubmitProgress.encode(message.progress, writer.uint32(74).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonSubmitBlocState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonSubmitBlocState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.errorCode = reader.int32() as any;
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.progress = CommonSubmitBlocState_SubmitProgress.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonSubmitBlocState {
    return {
      state: isSet(object.state) ? commonSubmitBlocState_StateFromJSON(object.state) : 0,
      errorCode: isSet(object.errorCode) ? commonSubmitBlocState_ErrorCodeFromJSON(object.errorCode) : 0,
      progress: isSet(object.progress) ? CommonSubmitBlocState_SubmitProgress.fromJSON(object.progress) : undefined,
    };
  },

  toJSON(message: CommonSubmitBlocState): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = commonSubmitBlocState_StateToJSON(message.state);
    }
    if (message.errorCode !== 0) {
      obj.errorCode = commonSubmitBlocState_ErrorCodeToJSON(message.errorCode);
    }
    if (message.progress !== undefined) {
      obj.progress = CommonSubmitBlocState_SubmitProgress.toJSON(message.progress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonSubmitBlocState>, I>>(base?: I): CommonSubmitBlocState {
    return CommonSubmitBlocState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonSubmitBlocState>, I>>(object: I): CommonSubmitBlocState {
    const message = createBaseCommonSubmitBlocState();
    message.state = object.state ?? 0;
    message.errorCode = object.errorCode ?? 0;
    message.progress = (object.progress !== undefined && object.progress !== null)
      ? CommonSubmitBlocState_SubmitProgress.fromPartial(object.progress)
      : undefined;
    return message;
  },
};

function createBaseCommonSubmitBlocState_SubmitProgress(): CommonSubmitBlocState_SubmitProgress {
  return { count: 0, total: 0 };
}

export const CommonSubmitBlocState_SubmitProgress = {
  encode(message: CommonSubmitBlocState_SubmitProgress, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.count !== 0) {
      writer.uint32(8).int32(message.count);
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CommonSubmitBlocState_SubmitProgress {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommonSubmitBlocState_SubmitProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.count = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommonSubmitBlocState_SubmitProgress {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: CommonSubmitBlocState_SubmitProgress): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommonSubmitBlocState_SubmitProgress>, I>>(
    base?: I,
  ): CommonSubmitBlocState_SubmitProgress {
    return CommonSubmitBlocState_SubmitProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommonSubmitBlocState_SubmitProgress>, I>>(
    object: I,
  ): CommonSubmitBlocState_SubmitProgress {
    const message = createBaseCommonSubmitBlocState_SubmitProgress();
    message.count = object.count ?? 0;
    message.total = object.total ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
