// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: hyttahub_implementation.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

export enum StorageEnum {
  cloud = 0,
  memory = 1,
  local = 2,
  UNRECOGNIZED = -1,
}

export function storageEnumFromJSON(object: any): StorageEnum {
  switch (object) {
    case 0:
    case "cloud":
      return StorageEnum.cloud;
    case 1:
    case "memory":
      return StorageEnum.memory;
    case 2:
    case "local":
      return StorageEnum.local;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StorageEnum.UNRECOGNIZED;
  }
}

export function storageEnumToJSON(object: StorageEnum): string {
  switch (object) {
    case StorageEnum.cloud:
      return "cloud";
    case StorageEnum.memory:
      return "memory";
    case StorageEnum.local:
      return "local";
    case StorageEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface HyttaHubImplementation {
  storage: StorageEnum;
  appBuildNumber: number;
  appId: string;
  firebaseRootCollection: string;
  disableFirestoreCache: boolean;
}

function createBaseHyttaHubImplementation(): HyttaHubImplementation {
  return { storage: 0, appBuildNumber: 0, appId: "", firebaseRootCollection: "", disableFirestoreCache: false };
}

export const HyttaHubImplementation = {
  encode(message: HyttaHubImplementation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.storage !== 0) {
      writer.uint32(8).int32(message.storage);
    }
    if (message.appBuildNumber !== 0) {
      writer.uint32(16).int32(message.appBuildNumber);
    }
    if (message.appId !== "") {
      writer.uint32(26).string(message.appId);
    }
    if (message.firebaseRootCollection !== "") {
      writer.uint32(34).string(message.firebaseRootCollection);
    }
    if (message.disableFirestoreCache !== false) {
      writer.uint32(40).bool(message.disableFirestoreCache);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HyttaHubImplementation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHyttaHubImplementation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.storage = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.appBuildNumber = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.appId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.firebaseRootCollection = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.disableFirestoreCache = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HyttaHubImplementation {
    return {
      storage: isSet(object.storage) ? storageEnumFromJSON(object.storage) : 0,
      appBuildNumber: isSet(object.appBuildNumber) ? globalThis.Number(object.appBuildNumber) : 0,
      appId: isSet(object.appId) ? globalThis.String(object.appId) : "",
      firebaseRootCollection: isSet(object.firebaseRootCollection)
        ? globalThis.String(object.firebaseRootCollection)
        : "",
      disableFirestoreCache: isSet(object.disableFirestoreCache)
        ? globalThis.Boolean(object.disableFirestoreCache)
        : false,
    };
  },

  toJSON(message: HyttaHubImplementation): unknown {
    const obj: any = {};
    if (message.storage !== 0) {
      obj.storage = storageEnumToJSON(message.storage);
    }
    if (message.appBuildNumber !== 0) {
      obj.appBuildNumber = Math.round(message.appBuildNumber);
    }
    if (message.appId !== "") {
      obj.appId = message.appId;
    }
    if (message.firebaseRootCollection !== "") {
      obj.firebaseRootCollection = message.firebaseRootCollection;
    }
    if (message.disableFirestoreCache !== false) {
      obj.disableFirestoreCache = message.disableFirestoreCache;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HyttaHubImplementation>, I>>(base?: I): HyttaHubImplementation {
    return HyttaHubImplementation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HyttaHubImplementation>, I>>(object: I): HyttaHubImplementation {
    const message = createBaseHyttaHubImplementation();
    message.storage = object.storage ?? 0;
    message.appBuildNumber = object.appBuildNumber ?? 0;
    message.appId = object.appId ?? "";
    message.firebaseRootCollection = object.firebaseRootCollection ?? "";
    message.disableFirestoreCache = object.disableFirestoreCache ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
