// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: service_replay_bloc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { BloomFilter } from "./bloom_filter";
import { CommonReplayStateEnum, commonReplayStateEnumFromJSON, commonReplayStateEnumToJSON } from "./common_blocs";

export const protobufPackage = "";

export interface ServiceAdmin {
  alias: string;
}

export interface ServiceReplayBlocState {
  minVersion: number;
  serviceUnavailable: boolean;
  terms: string;
  termsVersion: number;
  privacy: string;
  privacyVersion: number;
  state: CommonReplayStateEnum;
  /** map of event version to event data (base64 encoded) */
  events: { [key: number]: string };
  serviceAdmins: { [key: number]: ServiceAdmin };
  filter?:
    | BloomFilter
    | undefined;
  /** the instance of this event stream */
  instance: string;
  betaUsersFilter?: BloomFilter | undefined;
  removedServiceAdmins: { [key: number]: ServiceAdmin };
}

export interface ServiceReplayBlocState_EventsEntry {
  key: number;
  value: string;
}

export interface ServiceReplayBlocState_ServiceAdminsEntry {
  key: number;
  value?: ServiceAdmin | undefined;
}

export interface ServiceReplayBlocState_RemovedServiceAdminsEntry {
  key: number;
  value?: ServiceAdmin | undefined;
}

function createBaseServiceAdmin(): ServiceAdmin {
  return { alias: "" };
}

export const ServiceAdmin = {
  encode(message: ServiceAdmin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.alias !== "") {
      writer.uint32(10).string(message.alias);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceAdmin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceAdmin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.alias = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceAdmin {
    return { alias: isSet(object.alias) ? globalThis.String(object.alias) : "" };
  },

  toJSON(message: ServiceAdmin): unknown {
    const obj: any = {};
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceAdmin>, I>>(base?: I): ServiceAdmin {
    return ServiceAdmin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceAdmin>, I>>(object: I): ServiceAdmin {
    const message = createBaseServiceAdmin();
    message.alias = object.alias ?? "";
    return message;
  },
};

function createBaseServiceReplayBlocState(): ServiceReplayBlocState {
  return {
    minVersion: 0,
    serviceUnavailable: false,
    terms: "",
    termsVersion: 0,
    privacy: "",
    privacyVersion: 0,
    state: 0,
    events: {},
    serviceAdmins: {},
    filter: undefined,
    instance: "",
    betaUsersFilter: undefined,
    removedServiceAdmins: {},
  };
}

export const ServiceReplayBlocState = {
  encode(message: ServiceReplayBlocState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.minVersion !== 0) {
      writer.uint32(8).int32(message.minVersion);
    }
    if (message.serviceUnavailable !== false) {
      writer.uint32(16).bool(message.serviceUnavailable);
    }
    if (message.terms !== "") {
      writer.uint32(26).string(message.terms);
    }
    if (message.termsVersion !== 0) {
      writer.uint32(32).int32(message.termsVersion);
    }
    if (message.privacy !== "") {
      writer.uint32(42).string(message.privacy);
    }
    if (message.privacyVersion !== 0) {
      writer.uint32(48).int32(message.privacyVersion);
    }
    if (message.state !== 0) {
      writer.uint32(56).int32(message.state);
    }
    Object.entries(message.events).forEach(([key, value]) => {
      ServiceReplayBlocState_EventsEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).ldelim();
    });
    Object.entries(message.serviceAdmins).forEach(([key, value]) => {
      ServiceReplayBlocState_ServiceAdminsEntry.encode({ key: key as any, value }, writer.uint32(74).fork()).ldelim();
    });
    if (message.filter !== undefined) {
      BloomFilter.encode(message.filter, writer.uint32(82).fork()).ldelim();
    }
    if (message.instance !== "") {
      writer.uint32(90).string(message.instance);
    }
    if (message.betaUsersFilter !== undefined) {
      BloomFilter.encode(message.betaUsersFilter, writer.uint32(98).fork()).ldelim();
    }
    Object.entries(message.removedServiceAdmins).forEach(([key, value]) => {
      ServiceReplayBlocState_RemovedServiceAdminsEntry.encode({ key: key as any, value }, writer.uint32(106).fork())
        .ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceReplayBlocState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceReplayBlocState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.minVersion = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.serviceUnavailable = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.terms = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.termsVersion = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.privacy = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.privacyVersion = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          const entry8 = ServiceReplayBlocState_EventsEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.events[entry8.key] = entry8.value;
          }
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          const entry9 = ServiceReplayBlocState_ServiceAdminsEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.serviceAdmins[entry9.key] = entry9.value;
          }
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.filter = BloomFilter.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.instance = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.betaUsersFilter = BloomFilter.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          const entry13 = ServiceReplayBlocState_RemovedServiceAdminsEntry.decode(reader, reader.uint32());
          if (entry13.value !== undefined) {
            message.removedServiceAdmins[entry13.key] = entry13.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceReplayBlocState {
    return {
      minVersion: isSet(object.minVersion) ? globalThis.Number(object.minVersion) : 0,
      serviceUnavailable: isSet(object.serviceUnavailable) ? globalThis.Boolean(object.serviceUnavailable) : false,
      terms: isSet(object.terms) ? globalThis.String(object.terms) : "",
      termsVersion: isSet(object.termsVersion) ? globalThis.Number(object.termsVersion) : 0,
      privacy: isSet(object.privacy) ? globalThis.String(object.privacy) : "",
      privacyVersion: isSet(object.privacyVersion) ? globalThis.Number(object.privacyVersion) : 0,
      state: isSet(object.state) ? commonReplayStateEnumFromJSON(object.state) : 0,
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
      serviceAdmins: isObject(object.serviceAdmins)
        ? Object.entries(object.serviceAdmins).reduce<{ [key: number]: ServiceAdmin }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = ServiceAdmin.fromJSON(value);
          return acc;
        }, {})
        : {},
      filter: isSet(object.filter) ? BloomFilter.fromJSON(object.filter) : undefined,
      instance: isSet(object.instance) ? globalThis.String(object.instance) : "",
      betaUsersFilter: isSet(object.betaUsersFilter) ? BloomFilter.fromJSON(object.betaUsersFilter) : undefined,
      removedServiceAdmins: isObject(object.removedServiceAdmins)
        ? Object.entries(object.removedServiceAdmins).reduce<{ [key: number]: ServiceAdmin }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = ServiceAdmin.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: ServiceReplayBlocState): unknown {
    const obj: any = {};
    if (message.minVersion !== 0) {
      obj.minVersion = Math.round(message.minVersion);
    }
    if (message.serviceUnavailable !== false) {
      obj.serviceUnavailable = message.serviceUnavailable;
    }
    if (message.terms !== "") {
      obj.terms = message.terms;
    }
    if (message.termsVersion !== 0) {
      obj.termsVersion = Math.round(message.termsVersion);
    }
    if (message.privacy !== "") {
      obj.privacy = message.privacy;
    }
    if (message.privacyVersion !== 0) {
      obj.privacyVersion = Math.round(message.privacyVersion);
    }
    if (message.state !== 0) {
      obj.state = commonReplayStateEnumToJSON(message.state);
    }
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    if (message.serviceAdmins) {
      const entries = Object.entries(message.serviceAdmins);
      if (entries.length > 0) {
        obj.serviceAdmins = {};
        entries.forEach(([k, v]) => {
          obj.serviceAdmins[k] = ServiceAdmin.toJSON(v);
        });
      }
    }
    if (message.filter !== undefined) {
      obj.filter = BloomFilter.toJSON(message.filter);
    }
    if (message.instance !== "") {
      obj.instance = message.instance;
    }
    if (message.betaUsersFilter !== undefined) {
      obj.betaUsersFilter = BloomFilter.toJSON(message.betaUsersFilter);
    }
    if (message.removedServiceAdmins) {
      const entries = Object.entries(message.removedServiceAdmins);
      if (entries.length > 0) {
        obj.removedServiceAdmins = {};
        entries.forEach(([k, v]) => {
          obj.removedServiceAdmins[k] = ServiceAdmin.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceReplayBlocState>, I>>(base?: I): ServiceReplayBlocState {
    return ServiceReplayBlocState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceReplayBlocState>, I>>(object: I): ServiceReplayBlocState {
    const message = createBaseServiceReplayBlocState();
    message.minVersion = object.minVersion ?? 0;
    message.serviceUnavailable = object.serviceUnavailable ?? false;
    message.terms = object.terms ?? "";
    message.termsVersion = object.termsVersion ?? 0;
    message.privacy = object.privacy ?? "";
    message.privacyVersion = object.privacyVersion ?? 0;
    message.state = object.state ?? 0;
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.serviceAdmins = Object.entries(object.serviceAdmins ?? {}).reduce<{ [key: number]: ServiceAdmin }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = ServiceAdmin.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? BloomFilter.fromPartial(object.filter)
      : undefined;
    message.instance = object.instance ?? "";
    message.betaUsersFilter = (object.betaUsersFilter !== undefined && object.betaUsersFilter !== null)
      ? BloomFilter.fromPartial(object.betaUsersFilter)
      : undefined;
    message.removedServiceAdmins = Object.entries(object.removedServiceAdmins ?? {}).reduce<
      { [key: number]: ServiceAdmin }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = ServiceAdmin.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseServiceReplayBlocState_EventsEntry(): ServiceReplayBlocState_EventsEntry {
  return { key: 0, value: "" };
}

export const ServiceReplayBlocState_EventsEntry = {
  encode(message: ServiceReplayBlocState_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceReplayBlocState_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceReplayBlocState_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceReplayBlocState_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ServiceReplayBlocState_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceReplayBlocState_EventsEntry>, I>>(
    base?: I,
  ): ServiceReplayBlocState_EventsEntry {
    return ServiceReplayBlocState_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceReplayBlocState_EventsEntry>, I>>(
    object: I,
  ): ServiceReplayBlocState_EventsEntry {
    const message = createBaseServiceReplayBlocState_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseServiceReplayBlocState_ServiceAdminsEntry(): ServiceReplayBlocState_ServiceAdminsEntry {
  return { key: 0, value: undefined };
}

export const ServiceReplayBlocState_ServiceAdminsEntry = {
  encode(message: ServiceReplayBlocState_ServiceAdminsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      ServiceAdmin.encode(message.value, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceReplayBlocState_ServiceAdminsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceReplayBlocState_ServiceAdminsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = ServiceAdmin.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceReplayBlocState_ServiceAdminsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? ServiceAdmin.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ServiceReplayBlocState_ServiceAdminsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = ServiceAdmin.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceReplayBlocState_ServiceAdminsEntry>, I>>(
    base?: I,
  ): ServiceReplayBlocState_ServiceAdminsEntry {
    return ServiceReplayBlocState_ServiceAdminsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceReplayBlocState_ServiceAdminsEntry>, I>>(
    object: I,
  ): ServiceReplayBlocState_ServiceAdminsEntry {
    const message = createBaseServiceReplayBlocState_ServiceAdminsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? ServiceAdmin.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseServiceReplayBlocState_RemovedServiceAdminsEntry(): ServiceReplayBlocState_RemovedServiceAdminsEntry {
  return { key: 0, value: undefined };
}

export const ServiceReplayBlocState_RemovedServiceAdminsEntry = {
  encode(
    message: ServiceReplayBlocState_RemovedServiceAdminsEntry,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      ServiceAdmin.encode(message.value, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceReplayBlocState_RemovedServiceAdminsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceReplayBlocState_RemovedServiceAdminsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = ServiceAdmin.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceReplayBlocState_RemovedServiceAdminsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? ServiceAdmin.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ServiceReplayBlocState_RemovedServiceAdminsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = ServiceAdmin.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceReplayBlocState_RemovedServiceAdminsEntry>, I>>(
    base?: I,
  ): ServiceReplayBlocState_RemovedServiceAdminsEntry {
    return ServiceReplayBlocState_RemovedServiceAdminsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceReplayBlocState_RemovedServiceAdminsEntry>, I>>(
    object: I,
  ): ServiceReplayBlocState_RemovedServiceAdminsEntry {
    const message = createBaseServiceReplayBlocState_RemovedServiceAdminsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? ServiceAdmin.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
