// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: site_replay_bloc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Any } from "./any";
import { CommonReplayStateEnum, commonReplayStateEnumFromJSON, commonReplayStateEnumToJSON } from "./common_blocs";

export const protobufPackage = "";

export interface SiteReplayBlocState {
  state: CommonReplayStateEnum;
  /** base64 encoded events */
  events: { [key: number]: string };
  /** name of the site */
  name: string;
  /** map of user id to user info */
  members: { [key: number]: SiteReplayBlocState_Member };
  /** members that have been removed */
  removedMembers: { [key: number]: SiteReplayBlocState_Member };
  appBlocState?: Any | undefined;
}

export interface SiteReplayBlocState_Member {
  name: string;
  admin: boolean;
}

export interface SiteReplayBlocState_EventsEntry {
  key: number;
  value: string;
}

export interface SiteReplayBlocState_MembersEntry {
  key: number;
  value?: SiteReplayBlocState_Member | undefined;
}

export interface SiteReplayBlocState_RemovedMembersEntry {
  key: number;
  value?: SiteReplayBlocState_Member | undefined;
}

function createBaseSiteReplayBlocState(): SiteReplayBlocState {
  return { state: 0, events: {}, name: "", members: {}, removedMembers: {}, appBlocState: undefined };
}

export const SiteReplayBlocState = {
  encode(message: SiteReplayBlocState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    Object.entries(message.events).forEach(([key, value]) => {
      SiteReplayBlocState_EventsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).ldelim();
    });
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    Object.entries(message.members).forEach(([key, value]) => {
      SiteReplayBlocState_MembersEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).ldelim();
    });
    Object.entries(message.removedMembers).forEach(([key, value]) => {
      SiteReplayBlocState_RemovedMembersEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).ldelim();
    });
    if (message.appBlocState !== undefined) {
      Any.encode(message.appBlocState, writer.uint32(162).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteReplayBlocState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteReplayBlocState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          const entry2 = SiteReplayBlocState_EventsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.events[entry2.key] = entry2.value;
          }
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          const entry4 = SiteReplayBlocState_MembersEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.members[entry4.key] = entry4.value;
          }
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          const entry5 = SiteReplayBlocState_RemovedMembersEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.removedMembers[entry5.key] = entry5.value;
          }
          continue;
        case 20:
          if (tag !== 162) {
            break;
          }

          message.appBlocState = Any.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteReplayBlocState {
    return {
      state: isSet(object.state) ? commonReplayStateEnumFromJSON(object.state) : 0,
      events: isObject(object.events)
        ? Object.entries(object.events).reduce<{ [key: number]: string }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = String(value);
          return acc;
        }, {})
        : {},
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      members: isObject(object.members)
        ? Object.entries(object.members).reduce<{ [key: number]: SiteReplayBlocState_Member }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = SiteReplayBlocState_Member.fromJSON(value);
          return acc;
        }, {})
        : {},
      removedMembers: isObject(object.removedMembers)
        ? Object.entries(object.removedMembers).reduce<{ [key: number]: SiteReplayBlocState_Member }>(
          (acc, [key, value]) => {
            acc[globalThis.Number(key)] = SiteReplayBlocState_Member.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      appBlocState: isSet(object.appBlocState) ? Any.fromJSON(object.appBlocState) : undefined,
    };
  },

  toJSON(message: SiteReplayBlocState): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = commonReplayStateEnumToJSON(message.state);
    }
    if (message.events) {
      const entries = Object.entries(message.events);
      if (entries.length > 0) {
        obj.events = {};
        entries.forEach(([k, v]) => {
          obj.events[k] = v;
        });
      }
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.members) {
      const entries = Object.entries(message.members);
      if (entries.length > 0) {
        obj.members = {};
        entries.forEach(([k, v]) => {
          obj.members[k] = SiteReplayBlocState_Member.toJSON(v);
        });
      }
    }
    if (message.removedMembers) {
      const entries = Object.entries(message.removedMembers);
      if (entries.length > 0) {
        obj.removedMembers = {};
        entries.forEach(([k, v]) => {
          obj.removedMembers[k] = SiteReplayBlocState_Member.toJSON(v);
        });
      }
    }
    if (message.appBlocState !== undefined) {
      obj.appBlocState = Any.toJSON(message.appBlocState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteReplayBlocState>, I>>(base?: I): SiteReplayBlocState {
    return SiteReplayBlocState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteReplayBlocState>, I>>(object: I): SiteReplayBlocState {
    const message = createBaseSiteReplayBlocState();
    message.state = object.state ?? 0;
    message.events = Object.entries(object.events ?? {}).reduce<{ [key: number]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.name = object.name ?? "";
    message.members = Object.entries(object.members ?? {}).reduce<{ [key: number]: SiteReplayBlocState_Member }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = SiteReplayBlocState_Member.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.removedMembers = Object.entries(object.removedMembers ?? {}).reduce<
      { [key: number]: SiteReplayBlocState_Member }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = SiteReplayBlocState_Member.fromPartial(value);
      }
      return acc;
    }, {});
    message.appBlocState = (object.appBlocState !== undefined && object.appBlocState !== null)
      ? Any.fromPartial(object.appBlocState)
      : undefined;
    return message;
  },
};

function createBaseSiteReplayBlocState_Member(): SiteReplayBlocState_Member {
  return { name: "", admin: false };
}

export const SiteReplayBlocState_Member = {
  encode(message: SiteReplayBlocState_Member, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.admin !== false) {
      writer.uint32(16).bool(message.admin);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteReplayBlocState_Member {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteReplayBlocState_Member();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.admin = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteReplayBlocState_Member {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      admin: isSet(object.admin) ? globalThis.Boolean(object.admin) : false,
    };
  },

  toJSON(message: SiteReplayBlocState_Member): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.admin !== false) {
      obj.admin = message.admin;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteReplayBlocState_Member>, I>>(base?: I): SiteReplayBlocState_Member {
    return SiteReplayBlocState_Member.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteReplayBlocState_Member>, I>>(object: I): SiteReplayBlocState_Member {
    const message = createBaseSiteReplayBlocState_Member();
    message.name = object.name ?? "";
    message.admin = object.admin ?? false;
    return message;
  },
};

function createBaseSiteReplayBlocState_EventsEntry(): SiteReplayBlocState_EventsEntry {
  return { key: 0, value: "" };
}

export const SiteReplayBlocState_EventsEntry = {
  encode(message: SiteReplayBlocState_EventsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteReplayBlocState_EventsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteReplayBlocState_EventsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteReplayBlocState_EventsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SiteReplayBlocState_EventsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteReplayBlocState_EventsEntry>, I>>(base?: I): SiteReplayBlocState_EventsEntry {
    return SiteReplayBlocState_EventsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteReplayBlocState_EventsEntry>, I>>(
    object: I,
  ): SiteReplayBlocState_EventsEntry {
    const message = createBaseSiteReplayBlocState_EventsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSiteReplayBlocState_MembersEntry(): SiteReplayBlocState_MembersEntry {
  return { key: 0, value: undefined };
}

export const SiteReplayBlocState_MembersEntry = {
  encode(message: SiteReplayBlocState_MembersEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      SiteReplayBlocState_Member.encode(message.value, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteReplayBlocState_MembersEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteReplayBlocState_MembersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = SiteReplayBlocState_Member.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteReplayBlocState_MembersEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? SiteReplayBlocState_Member.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: SiteReplayBlocState_MembersEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = SiteReplayBlocState_Member.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteReplayBlocState_MembersEntry>, I>>(
    base?: I,
  ): SiteReplayBlocState_MembersEntry {
    return SiteReplayBlocState_MembersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteReplayBlocState_MembersEntry>, I>>(
    object: I,
  ): SiteReplayBlocState_MembersEntry {
    const message = createBaseSiteReplayBlocState_MembersEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? SiteReplayBlocState_Member.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseSiteReplayBlocState_RemovedMembersEntry(): SiteReplayBlocState_RemovedMembersEntry {
  return { key: 0, value: undefined };
}

export const SiteReplayBlocState_RemovedMembersEntry = {
  encode(message: SiteReplayBlocState_RemovedMembersEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      SiteReplayBlocState_Member.encode(message.value, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SiteReplayBlocState_RemovedMembersEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSiteReplayBlocState_RemovedMembersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = SiteReplayBlocState_Member.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SiteReplayBlocState_RemovedMembersEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? SiteReplayBlocState_Member.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: SiteReplayBlocState_RemovedMembersEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = SiteReplayBlocState_Member.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SiteReplayBlocState_RemovedMembersEntry>, I>>(
    base?: I,
  ): SiteReplayBlocState_RemovedMembersEntry {
    return SiteReplayBlocState_RemovedMembersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SiteReplayBlocState_RemovedMembersEntry>, I>>(
    object: I,
  ): SiteReplayBlocState_RemovedMembersEntry {
    const message = createBaseSiteReplayBlocState_RemovedMembersEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? SiteReplayBlocState_Member.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
