// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.12
// source: site_email.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

/** The SiteEmail is persisted in the email collection for each site */
export interface MarkForDeletion {
  /** the reason for deletion */
  deleteReason: MarkForDeletion_DeleteReason;
}

export enum MarkForDeletion_DeleteReason {
  /** memberLeftSite - update the site's */
  memberLeftSite = 0,
  /** memberRemovedFromSite - update the member's account stream */
  memberRemovedFromSite = 1,
  /** memberEmailUpdated - the user's email has been updated */
  memberEmailUpdated = 2,
  UNRECOGNIZED = -1,
}

export function markForDeletion_DeleteReasonFromJSON(object: any): MarkForDeletion_DeleteReason {
  switch (object) {
    case 0:
    case "memberLeftSite":
      return MarkForDeletion_DeleteReason.memberLeftSite;
    case 1:
    case "memberRemovedFromSite":
      return MarkForDeletion_DeleteReason.memberRemovedFromSite;
    case 2:
    case "memberEmailUpdated":
      return MarkForDeletion_DeleteReason.memberEmailUpdated;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MarkForDeletion_DeleteReason.UNRECOGNIZED;
  }
}

export function markForDeletion_DeleteReasonToJSON(object: MarkForDeletion_DeleteReason): string {
  switch (object) {
    case MarkForDeletion_DeleteReason.memberLeftSite:
      return "memberLeftSite";
    case MarkForDeletion_DeleteReason.memberRemovedFromSite:
      return "memberRemovedFromSite";
    case MarkForDeletion_DeleteReason.memberEmailUpdated:
      return "memberEmailUpdated";
    case MarkForDeletion_DeleteReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseMarkForDeletion(): MarkForDeletion {
  return { deleteReason: 0 };
}

export const MarkForDeletion = {
  encode(message: MarkForDeletion, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.deleteReason !== 0) {
      writer.uint32(8).int32(message.deleteReason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MarkForDeletion {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkForDeletion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.deleteReason = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarkForDeletion {
    return { deleteReason: isSet(object.deleteReason) ? markForDeletion_DeleteReasonFromJSON(object.deleteReason) : 0 };
  },

  toJSON(message: MarkForDeletion): unknown {
    const obj: any = {};
    if (message.deleteReason !== 0) {
      obj.deleteReason = markForDeletion_DeleteReasonToJSON(message.deleteReason);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarkForDeletion>, I>>(base?: I): MarkForDeletion {
    return MarkForDeletion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarkForDeletion>, I>>(object: I): MarkForDeletion {
    const message = createBaseMarkForDeletion();
    message.deleteReason = object.deleteReason ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
