// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kDebugMode, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name} '
      'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }

  static FirebaseOptions web =
      kDebugMode
          ? FirebaseOptions(
            apiKey: 'demo-project',
            appId: 'demo-project',
            messagingSenderId: '84331011964',
            projectId: 'demo-project',
            authDomain: 'demo-project.firebaseapp.com',
            storageBucket: 'demo-project.appspot.com', // <-- correct this
            measurementId: 'G-PG5EQTZ28S',
          )
          : throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for release web'
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
}
